# Postgres Examples, part B (14)

```{r setup, echo=FALSE, message=FALSE, warning=FALSE}
# These packages are called in almost every chapter of the book:
library(tidyverse)
library(DBI)
library(RPostgres)
library(glue)
library(here)
require(knitr)
library(dbplyr)
library(sqlpetr)
```

## Verify Docker is up and running:
```{r}
result <- system2("docker", "version", stdout = TRUE, stderr = TRUE)
result
```
verify pet DB is available, it may be stopped.
```{r}
result <- system2("docker", "ps -a", stdout = TRUE, stderr = TRUE)
result

any(grepl('Up .+pet$',result))

```
Start up the `docker-pet` container
```{r}
sp_docker_start("sql-pet")

```


now connect to the database with R
```{r}
con <- sp_get_postgres_connection(user = Sys.getenv("DEFAULT_POSTGRES_USER_NAME"),
                         password = Sys.getenv("DEFAULT_POSTGRES_PASSWORD"),
                         dbname = "dvdrental",
                         seconds_to_test = 10)
```
All of the material from this file has moved to files 71, 72, and 73.

Clean up
```{r}
# dbRemoveTable(con, "cars")
# dbRemoveTable(con, "mtcars")
# dbRemoveTable(con, "cust_movies")

# diconnect from the db
dbDisconnect(con)

sp_docker_stop("sql-pet")
```

