# Other resources {#chapter_appendix-other-resources}

## Editing this book
* Here are instructions for [editing this book](https://github.com/smithjd/sql-pet/blob/master/Contributing.md) 

## Docker alternatives
* Choosing [between Docker and Vagrant](https://medium.com/@Mahmoud_Zalt/vagrant-vs-docker-679c9ce4231b) [@Zait2017]

## Docker and R
* Noam Ross' [talk on Docker for the UseR](https://www.youtube.com/watch?v=803oZI5dvAU&t=1) [@Ross2018] and his [Slides](https://github.com/noamross/nyhackr-docker-talk) [@Ross2018a] give a lot of context and tips.
* Good Docker tutorials
  + [An introductory Docker tutorial](https://docker-curriculum.com/) [@Srivastav2018]
  + [A Docker curriculum](https://katacoda.com/courses/docker) [@Hall2018]
* Scott Came's materials about Docker and R [on his website](http://www.cascadia-analytics.com/2018/07/21/docker-r-p1.html) [@Came2018] and at the 2018 UseR Conference focus on **R inside Docker**.
* It's worth studying the [ROpensci Docker tutorial](https://ropenscilabs.github.io/r-docker-tutorial/) [@ROpenSciLabs2018]

## Documentation for Docker and PostgreSQL

* [The Postgres image documentation](https://docs.docker.com/samples/library/postgres/) [@Docker2018]
* PostgreSQL & Docker [documentation](https://docs.docker.com/samples/library/postgres/#postgres_db) [@Docker2018]
* [Dockerize PostgreSQL](https://docs.docker.com/engine/examples/postgresql_service/) [@Docker2018a]
* Usage examples of [PostgreSQL with Docker](https://amattn.com/p/tutorial_postgresql_usage_examples_with_docker.html) WARNING-EXPIRED CERTIFICATE 2018-12-20

## SQL and dplyr

* [Why SQL is not for analysis but dplyr is](https://blog.exploratory.io/why-sql-is-not-for-analysis-but-dplyr-is-5e180fef6aa7) [@Nishida2016]
* [Data Manipulation with dplyr (With 50 Examples)](https://www.listendata.com/2016/08/dplyr-tutorial.html) [@ListenData.com2016]

## More Resources
* David Severski describes some [key elements of connecting to databases with R](https://github.com/davidski/database_connections) for MacOS users [@Severski2018]
* This tutorial picks up ideas and tips from Ed Borasky's [Data Science pet containers](https://github.com/znmeb/data-science-pet-containers) [@Borasky2018], which creates a framework based on that [Hack Oregon example](https://github.com/hackoregon/data-science-pet-containers) and explains why this repo is named pet-sql.

