---
title: "Docker postgress test"
author: "John D. Smith"
date: "7/19/2018"
output: html_document
---

Trying to improve upon:
  https://github.com/Cascadia-R/Using_R_With_Databases/blob/master/Intro_To_R_With_Databases.Rmd

Using tips provided by Noam Ross:
  https://github.com/noamross/nyhackr-docker-talk

Install stevedore with:
  devtools::install_github("richfitz/stevedore", upgrade_dependencies = FALSE)
  
General documentation is here:
  https://richfitz.github.io/stevedore/articles/stevedore.html
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(DBI)
library(RPostgres)

# docker <- stevedore::docker_client()
# docker
# docker$volume
```
Running examples from: https://richfitz.github.io/stevedore/articles/examples.html
```{r}

con <- DBI::dbConnect(RPostgres::Postgres(),
                      host = "localhost",
                      port = "5432",
                      user = "postgres",
                      password = "postgres")
dbListTables(con)
dbListObjects(con)

dbWriteTable(con, "mtcars", mtcars)


dbRemoveTable(con, "mtcars")
dbExistsTable(con, "mtcars")

dbListFields(con, "mtcars")
dbReadTable(con, "mtcars")

dbDisconnect(con)
```
