#dvdrental_tables_declarations.R
actor_table <- DBI::dbReadTable(con,"actor")
address_table <- DBI::dbReadTable(con, "address")
category_table <- DBI::dbReadTable(con,"category")
city_table <- DBI::dbReadTable(con, "city")
country_table <- DBI::dbReadTable(con, "country")
customer_table <- DBI::dbReadTable(con, "customer")
film_table <- DBI::dbReadTable(con, "film")
film_actor_table <- DBI::dbReadTable(con, "film_actor")
film_category_table <- DBI::dbReadTable(con, "film_category")
inventory_table <- DBI::dbReadTable(con, "inventory")
language_table <- DBI::dbReadTable(con, "language")
rental_table <- DBI::dbReadTable(con, "rental")
payment_table <- DBI::dbReadTable(con, "payment")
staff_table <- DBI::dbReadTable(con, "staff")
store_table <- DBI::dbReadTable(con, "store")