---
title: "test-graph"
author: "John D. Smith"
date: "12/5/2019"
output: html_document
---

```{r setup, include=FALSE}
library(DiagrammeR)

```

```{r}
table_list <- c("sales_order_header", 
"sales_person", 
"employee", 
"person", 
"sales_territory"
)

grViz("
digraph a_nice_graph {

# node definitions with substituted label text
node [fontname = Helvetica]
b [label = '@@2-1']
c [label = '@@2-2']
d [label = '@@2-3']
e [label = '@@2-4']
f [label = '@@2-5']
g [label = '@@2-6']
h [label = '@@2-7']
i [label = '@@2-8']
j [label = '@@2-9']

# edge definitions with the node IDs
# a -> {b c d e f g h i j}
a -> b -> c
}

[1]: 'top'
[2]: tables
")
```

```{r}
grViz("
digraph boxes_and_circles {

  # a 'graph' statement
  graph [overlap = true, fontsize = 10]

  # several 'node' statements
  node [shape = box,
        fontname = Helvetica]
  A; B; C; D; E; F

  node [shape = circle,
        fixedsize = true,
        width = 0.9] // sets as circles
  1; 2; 3; 4; 5; 6; 7; 8

  # several 'edge' statements
  A->1 B->2 B->3 B->4 C->A
  1->D E->A 2->4 1->5 1->F
  E->6 4->6 5->7 6->7 3->8
}
[1]: 'junk'
")
```

