---
title: "Introduction to sqlpetr"
author: "M. Edward (Ed) Borasky"
date: "3/6/2019"
output:
  beamer_presentation: 
    theme: EastLansing
  ioslides_presentation: default
  slidy_presentation: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Getting Set Up

## Prerequisites

* R 3.5.0 or later
* RStudio (Preview) 1.2.1303 or later
* Docker Community Edition (18.09 or later)

## Optional
* Git for version control
* pgAdmin4 for PostgreSQL database administration

## Windows requirments
* 64-bit Intel / AMD processor with virtualization hardware enabled
* Windows 10 Pro with Hyper-V virtualizer enabled
* Docker for Windows
* 4 GB of RAM or greater

## Linux requirements
* 64-bit Intel / AMD processor with virtualization hardware enabled
* Docker CE supported distro
    - Fedora 29
    - Ubuntu 18.04.2 LTS "Bionic Beaver"
    - Debian 9.6 "stretch"
    - Arch Linux with Arch User Repository (AUR) and AUR helper `yay`
* Docker Community Edition (use Arch `docker` package on Arch)
* 4 GB of RAM or greater

# Docker Concepts

## Images

## Containers

## Networks

## Volumes

## Registries

# PostgreSQL Database Administration 101

## Clusters, databases and schemas

## Users / Roles

## Tables, views and materialized views

## Making a connection

## pgAdmin
