# Interacting with Postgres from R

## Topics to cover
* keeping passwords secure
* differences between production and data warehouse environments
* overview investigation: do you understand your data
  + documentation and its limits
  + find out how the data is used by those who enter it and others who've used it before
  + what's *missing* from the database: (columns, records, cells)
  + why is there missing data?
* dplyr queries
* examining dplyr queries (show_query on the R side v EXPLAIN on the Postges side)
* performance considerations: get it to work, then optimize
* Tradeoffs between leaving the data in Postgres vs what's kept in R: 
  + browsing the data
  + larger samples and complete tables
  + using what you know to write efficient queries that do most of the work on the server
* learning to keep your DBAs happy

## More topics
* from [Aaron Makubuya's workshop](https://github.com/Cascadia-R/Using_R_With_Databases/blob/master/Intro_To_R_With_Databases.Rmd) at the Cascadia R Conf.

  + SELECT * vs SELECT list of columns
  + controlling the number of rows returned with WHERE 
  + Glue for constructing SQL statements vs dplyr
  + JOIN flavors
  + parameterizing SQL queries
  + show_query and EXPLAIN
  
