# Postgres Examples, part B (14)

```{r setup, include=FALSE}
source('r-database-docker/book-src/standard-package-list.R')
```

```{r echo=FALSE}
read_chunk('book-src/db-login-batch-code.R')

# source('book-src/shared-db-login-batch-code.R')  # use when debugging outside of knitr
```

```{r get_postgres_connection, eval=TRUE, echo=FALSE}

```

## Verify Docker is up and running:
```{r}
result <- system2("docker", "version", stdout = TRUE, stderr = TRUE)
result
```
verify pet DB is available, it may be stopped.
```{r}
result <- system2("docker", "ps -a", stdout = TRUE, stderr = TRUE)
result

any(grepl('Up .+pet$',result))

```
Start up the `docker-pet` container
```{r}
result <- system2("docker", "start sql-pet", stdout = TRUE, stderr = TRUE)
result


```


now connect to the database with R
```{r}

con <- wait_for_postgres(user = Sys.getenv("DEFAULT_POSTGRES_USER_NAME"),
                         password = Sys.getenv("DEFAULT_POSTGRES_PASSWORD"),
                         dbname = "dvdrental",
                         seconds_to_test = 10)
```
All of the material from this file has moved to files 71, 72, and 73.

Clean up
```{r}
# dbRemoveTable(con, "cars")
# dbRemoveTable(con, "mtcars")
# dbRemoveTable(con, "cust_movies")

# diconnect from the db
dbDisconnect(con)

result <- system2("docker", "stop sql-pet", stdout = TRUE, stderr = TRUE)
result

```

