---
title: "R, Databases and Docker"
author: "M. Edward (Ed) Borasky, editor"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: "A collection of tutorials for integrating R with databases using Docker"
---

# Introduction

## Why integrate R with databases using Docker?

* Large data stores in organizations are stored in databases that have specific access constraints and  structural characteristics.
* Learning to navigate the gap between R and the database is difficult to simulate outside corporate walls.
* R users frequently need to make sense of complex data structures using diagnostic techniques that shuld not be reinvented (and so would benefit from more public instruction and  commentary).
* Docker is a relatively easy way to simulate the relationship between an R/Rstudio session and database -- all on on a single machine.

## Who are we?

* M. Edward (Ed) Borasky - [\@znmeb](https://github.com/znmeb)
* John David Smith - [\@smithjd](https://github.com/smithjd)
* Scott Came - [\@scottcame](https://github.com/scottcame)
* Ian Franz - [\@ianfrantz](https://github.com/ianfrantz)
* Sophie Yang - [\@SophieMYang](https://github.com/SophieMYang)
* Jim Tyhurst - [\@jimtyhurst](https://github.com/jimtyhurst)

## Prerequisites
You will need

* A computer running Windows, MacOS, or Linux. Any Linux distro that will run Docker Community Edition, R and RStudio will work,
* R, and
* Docker hosting.

The database we use is PostgreSQL 10, but you do not need to install that - it's installed via a Docker image. RStudio 1.2 is highly recommended but not required.

```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(),
  'docker',
  'tidyverse'
), 'packages.bib')
```
