<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>R, Databases and Docker</title>
  <meta name="description" content="A collection of tutorials for integrating R with databases using Docker">
  <meta name="generator" content="bookdown 0.7 and GitBook 2.6.7">

  <meta property="og:title" content="R, Databases and Docker" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="A collection of tutorials for integrating R with databases using Docker" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="R, Databases and Docker" />
  
  <meta name="twitter:description" content="A collection of tutorials for integrating R with databases using Docker" />
  

<meta name="author" content="Dipti Muni, Ian Frantz, John David Smith, Mary Anne Thygesen, M. Edward (Ed) Borasky, Scott Case, and Sophie Yang">


<meta name="date" content="2018-10-26">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="joins-and-complex-queries-13.html">
<link rel="next" href="sql-be-12-and-or-logical-precedence.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />







<script src="libs/htmlwidgets-1.3/htmlwidgets.js"></script>
<script src="libs/viz-0.3/viz.js"></script>
<link href="libs/DiagrammeR-styles-0.2/styles.css" rel="stylesheet" />
<script src="libs/grViz-binding-1.0.0/grViz.js"></script>
<link href="libs/datatables-css-0.0.0/datatables-crosstalk.css" rel="stylesheet" />
<script src="libs/datatables-binding-0.4/datatables.js"></script>
<link href="libs/dt-core-1.10.16/css/jquery.dataTables.min.css" rel="stylesheet" />
<link href="libs/dt-core-1.10.16/css/jquery.dataTables.extra.css" rel="stylesheet" />
<script src="libs/dt-core-1.10.16/js/jquery.dataTables.min.js"></script>
<link href="libs/crosstalk-1.0.0/css/crosstalk.css" rel="stylesheet" />
<script src="libs/crosstalk-1.0.0/js/crosstalk.min.js"></script>
<script src="libs/d3-3.3.8/d3.min.js"></script>
<script src="libs/dagre-0.4.0/dagre-d3.min.js"></script>
<link href="libs/mermaid-0.3.0/dist/mermaid.css" rel="stylesheet" />
<script src="libs/mermaid-0.3.0/dist/mermaid.slim.min.js"></script>
<script src="libs/chromatography-0.1/chromatography.js"></script>
<script src="libs/DiagrammeR-binding-1.0.0/DiagrammeR.js"></script>


<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; position: absolute; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; }
pre.numberSource a.sourceLine:empty
  { position: absolute; }
pre.numberSource a.sourceLine::before
  { content: attr(data-line-number);
    position: absolute; left: -5em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">R, Databases and Docker</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Introduction</a><ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#using-r-to-query-a-dbms-in-your-organization"><i class="fa fa-check"></i><b>1.1</b> Using R to query a DBMS in your organization</a></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#docker-as-a-tool-for-users"><i class="fa fa-check"></i><b>1.2</b> Docker as a tool for UseRs</a></li>
<li class="chapter" data-level="1.3" data-path="index.html"><a href="index.html#why-write-a-book-about-dbms-access-from-r-using-docker"><i class="fa fa-check"></i><b>1.3</b> Why write a book about DBMS access from R using Docker?</a></li>
<li class="chapter" data-level="1.4" data-path="index.html"><a href="index.html#docker-and-r-on-your-machine"><i class="fa fa-check"></i><b>1.4</b> Docker and R on your machine</a></li>
<li class="chapter" data-level="1.5" data-path="index.html"><a href="index.html#who-are-we"><i class="fa fa-check"></i><b>1.5</b> Who are we?</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="how-to-use-this-book-01.html"><a href="how-to-use-this-book-01.html"><i class="fa fa-check"></i><b>2</b> How to use this book (01)</a><ul>
<li class="chapter" data-level="2.1" data-path="how-to-use-this-book-01.html"><a href="how-to-use-this-book-01.html#prerequisites"><i class="fa fa-check"></i><b>2.1</b> Prerequisites</a></li>
<li class="chapter" data-level="2.2" data-path="how-to-use-this-book-01.html"><a href="how-to-use-this-book-01.html#installing-docker"><i class="fa fa-check"></i><b>2.2</b> Installing Docker</a></li>
<li class="chapter" data-level="2.3" data-path="how-to-use-this-book-01.html"><a href="how-to-use-this-book-01.html#download-the-repo"><i class="fa fa-check"></i><b>2.3</b> Download the repo</a></li>
<li class="chapter" data-level="2.4" data-path="how-to-use-this-book-01.html"><a href="how-to-use-this-book-01.html#read-along-experiment-as-you-go"><i class="fa fa-check"></i><b>2.4</b> Read along, experiment as you go</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="docker-hosting-for-windows-02.html"><a href="docker-hosting-for-windows-02.html"><i class="fa fa-check"></i><b>3</b> Docker Hosting for Windows (02)</a><ul>
<li class="chapter" data-level="3.1" data-path="docker-hosting-for-windows-02.html"><a href="docker-hosting-for-windows-02.html#hardware-requirements"><i class="fa fa-check"></i><b>3.1</b> Hardware requirements</a></li>
<li class="chapter" data-level="3.2" data-path="docker-hosting-for-windows-02.html"><a href="docker-hosting-for-windows-02.html#software-requirements"><i class="fa fa-check"></i><b>3.2</b> Software requirements</a><ul>
<li class="chapter" data-level="3.2.1" data-path="docker-hosting-for-windows-02.html"><a href="docker-hosting-for-windows-02.html#windows-7-8-8.1-and-windows-10-home-64-bit"><i class="fa fa-check"></i><b>3.2.1</b> Windows 7, 8, 8.1 and Windows 10 Home (64 bit)</a></li>
<li class="chapter" data-level="3.2.2" data-path="docker-hosting-for-windows-02.html"><a href="docker-hosting-for-windows-02.html#windows-10-pro"><i class="fa fa-check"></i><b>3.2.2</b> Windows 10 Pro</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="docker-hosting-for-windows-02.html"><a href="docker-hosting-for-windows-02.html#docker-for-windows-settings"><i class="fa fa-check"></i><b>3.3</b> Docker for Windows settings</a><ul>
<li class="chapter" data-level="3.3.1" data-path="docker-hosting-for-windows-02.html"><a href="docker-hosting-for-windows-02.html#shared-drives"><i class="fa fa-check"></i><b>3.3.1</b> Shared drives</a></li>
<li class="chapter" data-level="3.3.2" data-path="docker-hosting-for-windows-02.html"><a href="docker-hosting-for-windows-02.html#kubernetes"><i class="fa fa-check"></i><b>3.3.2</b> Kubernetes</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="docker-hosting-for-windows-02.html"><a href="docker-hosting-for-windows-02.html#git-github-and-line-endings"><i class="fa fa-check"></i><b>3.4</b> Git, GitHub and line endings</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="this-books-learning-goals-and-use-cases-03.html"><a href="this-books-learning-goals-and-use-cases-03.html"><i class="fa fa-check"></i><b>4</b> This Book’s Learning Goals and Use Cases (03)</a><ul>
<li class="chapter" data-level="4.1" data-path="this-books-learning-goals-and-use-cases-03.html"><a href="this-books-learning-goals-and-use-cases-03.html#learning-goals"><i class="fa fa-check"></i><b>4.1</b> Learning Goals</a></li>
<li class="chapter" data-level="4.2" data-path="this-books-learning-goals-and-use-cases-03.html"><a href="this-books-learning-goals-and-use-cases-03.html#imaging-a-dvd-rental-business"><i class="fa fa-check"></i><b>4.2</b> Imaging a DVD rental business</a></li>
<li class="chapter" data-level="4.3" data-path="this-books-learning-goals-and-use-cases-03.html"><a href="this-books-learning-goals-and-use-cases-03.html#use-cases"><i class="fa fa-check"></i><b>4.3</b> Use cases</a></li>
<li class="chapter" data-level="4.4" data-path="this-books-learning-goals-and-use-cases-03.html"><a href="this-books-learning-goals-and-use-cases-03.html#investigating-a-question-using-with-an-organizations-database"><i class="fa fa-check"></i><b>4.4</b> Investigating a question using with an organization’s database</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="docker-postgres-and-r-04.html"><a href="docker-postgres-and-r-04.html"><i class="fa fa-check"></i><b>5</b> Docker, Postgres, and R (04)</a><ul>
<li class="chapter" data-level="5.1" data-path="docker-postgres-and-r-04.html"><a href="docker-postgres-and-r-04.html#verify-that-docker-is-running"><i class="fa fa-check"></i><b>5.1</b> Verify that Docker is running</a></li>
<li class="chapter" data-level="5.2" data-path="docker-postgres-and-r-04.html"><a href="docker-postgres-and-r-04.html#clean-up-if-appropriate"><i class="fa fa-check"></i><b>5.2</b> Clean up if appropriate</a></li>
<li class="chapter" data-level="5.3" data-path="docker-postgres-and-r-04.html"><a href="docker-postgres-and-r-04.html#connect-read-and-write-to-postgres-from-r"><i class="fa fa-check"></i><b>5.3</b> Connect, read and write to Postgres from R</a><ul>
<li class="chapter" data-level="5.3.1" data-path="docker-postgres-and-r-04.html"><a href="docker-postgres-and-r-04.html#pause-for-some-security-considerations"><i class="fa fa-check"></i><b>5.3.1</b> Pause for some security considerations</a></li>
<li class="chapter" data-level="5.3.2" data-path="docker-postgres-and-r-04.html"><a href="docker-postgres-and-r-04.html#alternative-put-the-database-password-in-an-environment-file"><i class="fa fa-check"></i><b>5.3.2</b> Alternative: put the database password in an environment file</a></li>
<li class="chapter" data-level="5.3.3" data-path="docker-postgres-and-r-04.html"><a href="docker-postgres-and-r-04.html#interact-with-postgres"><i class="fa fa-check"></i><b>5.3.3</b> Interact with Postgres</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="docker-postgres-and-r-04.html"><a href="docker-postgres-and-r-04.html#clean-up"><i class="fa fa-check"></i><b>5.4</b> Clean up</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="the-dvdrental-database-in-postgres-in-docker-05.html"><a href="the-dvdrental-database-in-postgres-in-docker-05.html"><i class="fa fa-check"></i><b>6</b> The dvdrental database in Postgres in Docker (05)</a><ul>
<li class="chapter" data-level="6.1" data-path="the-dvdrental-database-in-postgres-in-docker-05.html"><a href="the-dvdrental-database-in-postgres-in-docker-05.html#overview"><i class="fa fa-check"></i><b>6.1</b> Overview</a></li>
<li class="chapter" data-level="6.2" data-path="the-dvdrental-database-in-postgres-in-docker-05.html"><a href="the-dvdrental-database-in-postgres-in-docker-05.html#verify-that-docker-is-up-and-running"><i class="fa fa-check"></i><b>6.2</b> Verify that Docker is up and running</a></li>
<li class="chapter" data-level="6.3" data-path="the-dvdrental-database-in-postgres-in-docker-05.html"><a href="the-dvdrental-database-in-postgres-in-docker-05.html#clean-up-if-appropriate-1"><i class="fa fa-check"></i><b>6.3</b> Clean up if appropriate</a></li>
<li class="chapter" data-level="6.4" data-path="the-dvdrental-database-in-postgres-in-docker-05.html"><a href="the-dvdrental-database-in-postgres-in-docker-05.html#build-the-docker-image"><i class="fa fa-check"></i><b>6.4</b> Build the Docker Image</a></li>
<li class="chapter" data-level="6.5" data-path="the-dvdrental-database-in-postgres-in-docker-05.html"><a href="the-dvdrental-database-in-postgres-in-docker-05.html#run-the-docker-image"><i class="fa fa-check"></i><b>6.5</b> Run the Docker Image</a></li>
<li class="chapter" data-level="6.6" data-path="the-dvdrental-database-in-postgres-in-docker-05.html"><a href="the-dvdrental-database-in-postgres-in-docker-05.html#connect-to-postgres-with-r"><i class="fa fa-check"></i><b>6.6</b> Connect to Postgres with R</a></li>
<li class="chapter" data-level="6.7" data-path="the-dvdrental-database-in-postgres-in-docker-05.html"><a href="the-dvdrental-database-in-postgres-in-docker-05.html#stop-and-start-to-demonstrate-persistence"><i class="fa fa-check"></i><b>6.7</b> Stop and start to demonstrate persistence</a></li>
<li class="chapter" data-level="6.8" data-path="the-dvdrental-database-in-postgres-in-docker-05.html"><a href="the-dvdrental-database-in-postgres-in-docker-05.html#cleaning-up"><i class="fa fa-check"></i><b>6.8</b> Cleaning up</a></li>
<li class="chapter" data-level="6.9" data-path="the-dvdrental-database-in-postgres-in-docker-05.html"><a href="the-dvdrental-database-in-postgres-in-docker-05.html#using-the-sql-pet-container-in-the-rest-of-the-book"><i class="fa fa-check"></i><b>6.9</b> Using the <code>sql-pet</code> container in the rest of the book</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="mapping-your-local-environment-10.html"><a href="mapping-your-local-environment-10.html"><i class="fa fa-check"></i><b>7</b> Mapping your local environment (10)</a><ul>
<li class="chapter" data-level="7.1" data-path="mapping-your-local-environment-10.html"><a href="mapping-your-local-environment-10.html#basics"><i class="fa fa-check"></i><b>7.1</b> Basics</a></li>
<li class="chapter" data-level="7.2" data-path="mapping-your-local-environment-10.html"><a href="mapping-your-local-environment-10.html#ask-yourself-what-are-you-aiming-for"><i class="fa fa-check"></i><b>7.2</b> Ask yourself, what are you aiming for?</a></li>
<li class="chapter" data-level="7.3" data-path="mapping-your-local-environment-10.html"><a href="mapping-your-local-environment-10.html#get-some-basic-information-about-your-database"><i class="fa fa-check"></i><b>7.3</b> Get some basic information about your database</a></li>
<li class="chapter" data-level="7.4" data-path="mapping-your-local-environment-10.html"><a href="mapping-your-local-environment-10.html#tutorial-environment"><i class="fa fa-check"></i><b>7.4</b> Tutorial Environment</a></li>
<li class="chapter" data-level="7.5" data-path="mapping-your-local-environment-10.html"><a href="mapping-your-local-environment-10.html#communicating-with-docker-applications"><i class="fa fa-check"></i><b>7.5</b> Communicating with Docker Applications</a></li>
<li class="chapter" data-level="7.6" data-path="mapping-your-local-environment-10.html"><a href="mapping-your-local-environment-10.html#exercises"><i class="fa fa-check"></i><b>7.6</b> Exercises</a><ul>
<li class="chapter" data-level="7.6.1" data-path="mapping-your-local-environment-10.html"><a href="mapping-your-local-environment-10.html#docker-help"><i class="fa fa-check"></i><b>7.6.1</b> Docker Help</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="introduction-to-dbms-queries-11.html"><a href="introduction-to-dbms-queries-11.html"><i class="fa fa-check"></i><b>8</b> Introduction to DBMS queries (11)</a><ul>
<li class="chapter" data-level="8.1" data-path="introduction-to-dbms-queries-11.html"><a href="introduction-to-dbms-queries-11.html#downloading-the-data-from-the-database"><i class="fa fa-check"></i><b>8.1</b> Downloading the data from the database</a><ul>
<li class="chapter" data-level="8.1.1" data-path="introduction-to-dbms-queries-11.html"><a href="introduction-to-dbms-queries-11.html#finding-out-whats-there"><i class="fa fa-check"></i><b>8.1.1</b> Finding out what’s there</a></li>
<li class="chapter" data-level="8.1.2" data-path="introduction-to-dbms-queries-11.html"><a href="introduction-to-dbms-queries-11.html#downloading-an-entire-table"><i class="fa fa-check"></i><b>8.1.2</b> Downloading an entire table</a></li>
<li class="chapter" data-level="8.1.3" data-path="introduction-to-dbms-queries-11.html"><a href="introduction-to-dbms-queries-11.html#referencing-a-table-for-many-different-purposes"><i class="fa fa-check"></i><b>8.1.3</b> Referencing a table for many different purposes</a></li>
<li class="chapter" data-level="8.1.4" data-path="introduction-to-dbms-queries-11.html"><a href="introduction-to-dbms-queries-11.html#sub-setting-variables"><i class="fa fa-check"></i><b>8.1.4</b> Sub-setting variables</a></li>
<li class="chapter" data-level="8.1.5" data-path="introduction-to-dbms-queries-11.html"><a href="introduction-to-dbms-queries-11.html#controlling-number-of-rows-returned"><i class="fa fa-check"></i><b>8.1.5</b> Controlling number of rows returned</a></li>
<li class="chapter" data-level="8.1.6" data-path="introduction-to-dbms-queries-11.html"><a href="introduction-to-dbms-queries-11.html#random-rows-from-the-dbms"><i class="fa fa-check"></i><b>8.1.6</b> Random rows from the dbms</a></li>
<li class="chapter" data-level="8.1.7" data-path="introduction-to-dbms-queries-11.html"><a href="introduction-to-dbms-queries-11.html#examining-dplyrs-sql-query-and-re-using-sql-code"><i class="fa fa-check"></i><b>8.1.7</b> Examining <code>dplyr</code>’s SQL query and re-using SQL code</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="introduction-to-dbms-queries-11.html"><a href="introduction-to-dbms-queries-11.html#investigating-a-single-table-with-r"><i class="fa fa-check"></i><b>8.2</b> Investigating a single table with R</a><ul>
<li class="chapter" data-level="8.2.1" data-path="introduction-to-dbms-queries-11.html"><a href="introduction-to-dbms-queries-11.html#str---a-base-package-workhorse"><i class="fa fa-check"></i><b>8.2.1</b> <code>str</code> - a base package workhorse</a></li>
<li class="chapter" data-level="8.2.2" data-path="introduction-to-dbms-queries-11.html"><a href="introduction-to-dbms-queries-11.html#always-just-look-at-your-data-with-head-view-or-kable"><i class="fa fa-check"></i><b>8.2.2</b> Always just <strong>look</strong> at your data with <code>head</code>, <code>View</code>, or <code>kable</code></a></li>
<li class="chapter" data-level="8.2.3" data-path="introduction-to-dbms-queries-11.html"><a href="introduction-to-dbms-queries-11.html#the-summary-function-in-base"><i class="fa fa-check"></i><b>8.2.3</b> The <code>summary</code> function in base</a></li>
<li class="chapter" data-level="8.2.4" data-path="introduction-to-dbms-queries-11.html"><a href="introduction-to-dbms-queries-11.html#the-glimpse-function-in-the-tibble-package"><i class="fa fa-check"></i><b>8.2.4</b> The <code>glimpse</code> function in the <code>tibble</code> package</a></li>
<li class="chapter" data-level="8.2.5" data-path="introduction-to-dbms-queries-11.html"><a href="introduction-to-dbms-queries-11.html#the-skim-function-in-the-skmir-package"><i class="fa fa-check"></i><b>8.2.5</b> The <code>skim</code> function in the <code>skmir</code> package</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="introduction-to-dbms-queries-11.html"><a href="introduction-to-dbms-queries-11.html#dividing-the-work-between-r-on-your-machine-and-the-dbms"><i class="fa fa-check"></i><b>8.3</b> Dividing the work between R on your machine and the DBMS</a><ul>
<li class="chapter" data-level="8.3.1" data-path="introduction-to-dbms-queries-11.html"><a href="introduction-to-dbms-queries-11.html#make-the-server-do-as-much-work-as-you-can"><i class="fa fa-check"></i><b>8.3.1</b> Make the server do as much work as you can</a></li>
<li class="chapter" data-level="8.3.2" data-path="introduction-to-dbms-queries-11.html"><a href="introduction-to-dbms-queries-11.html#criteria-for-choosing-between-dplyr-and-native-sql"><i class="fa fa-check"></i><b>8.3.2</b> Criteria for choosing between <code>dplyr</code> and native SQL</a></li>
<li class="chapter" data-level="8.3.3" data-path="introduction-to-dbms-queries-11.html"><a href="introduction-to-dbms-queries-11.html#dplyr-tools"><i class="fa fa-check"></i><b>8.3.3</b> <code>dplyr</code> tools</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="introduction-to-dbms-queries-11.html"><a href="introduction-to-dbms-queries-11.html#other-resources"><i class="fa fa-check"></i><b>8.4</b> Other resources</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="explain-queries-11a.html"><a href="explain-queries-11a.html"><i class="fa fa-check"></i><b>9</b> Explain queries (11a)</a></li>
<li class="chapter" data-level="10" data-path="joins-and-complex-queries-13.html"><a href="joins-and-complex-queries-13.html"><i class="fa fa-check"></i><b>10</b> Joins and complex queries (13)</a><ul>
<li class="chapter" data-level="10.1" data-path="joins-and-complex-queries-13.html"><a href="joins-and-complex-queries-13.html#joins"><i class="fa fa-check"></i><b>10.1</b> Joins</a><ul>
<li class="chapter" data-level="10.1.1" data-path="joins-and-complex-queries-13.html"><a href="joins-and-complex-queries-13.html#union"><i class="fa fa-check"></i><b>10.1.1</b> Union</a></li>
</ul></li>
<li class="chapter" data-level="10.2" data-path="joins-and-complex-queries-13.html"><a href="joins-and-complex-queries-13.html#store-analysis"><i class="fa fa-check"></i><b>10.2</b> Store analysis</a><ul>
<li class="chapter" data-level="10.2.1" data-path="joins-and-complex-queries-13.html"><a href="joins-and-complex-queries-13.html#which-store-has-had-more-rentals-and-income"><i class="fa fa-check"></i><b>10.2.1</b> which store has had more rentals and income</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="joins-and-complex-queries-13.html"><a href="joins-and-complex-queries-13.html#store-analysis-1"><i class="fa fa-check"></i><b>10.3</b> Store analysis</a><ul>
<li class="chapter" data-level="10.3.1" data-path="joins-and-complex-queries-13.html"><a href="joins-and-complex-queries-13.html#which-store-has-the-largest-income-stream"><i class="fa fa-check"></i><b>10.3.1</b> which store has the largest income stream?</a></li>
<li class="chapter" data-level="10.3.2" data-path="joins-and-complex-queries-13.html"><a href="joins-and-complex-queries-13.html#how-many-rentals-have-not-been-paid"><i class="fa fa-check"></i><b>10.3.2</b> How many rentals have not been paid</a></li>
<li class="chapter" data-level="10.3.3" data-path="joins-and-complex-queries-13.html"><a href="joins-and-complex-queries-13.html#how-many-rentals-have-been-paid"><i class="fa fa-check"></i><b>10.3.3</b> How many rentals have been paid</a></li>
<li class="chapter" data-level="10.3.4" data-path="joins-and-complex-queries-13.html"><a href="joins-and-complex-queries-13.html#how-much-has-been-paid"><i class="fa fa-check"></i><b>10.3.4</b> How much has been paid</a></li>
<li class="chapter" data-level="10.3.5" data-path="joins-and-complex-queries-13.html"><a href="joins-and-complex-queries-13.html#what-is-the-average-pricemovie"><i class="fa fa-check"></i><b>10.3.5</b> What is the average price/movie</a></li>
<li class="chapter" data-level="10.3.6" data-path="joins-and-complex-queries-13.html"><a href="joins-and-complex-queries-13.html#estimate-the-outstanding-balance"><i class="fa fa-check"></i><b>10.3.6</b> Estimate the outstanding balance</a></li>
<li class="chapter" data-level="10.3.7" data-path="joins-and-complex-queries-13.html"><a href="joins-and-complex-queries-13.html#what-is-the-actual-outstanding-balance"><i class="fa fa-check"></i><b>10.3.7</b> what is the actual outstanding balance</a></li>
<li class="chapter" data-level="10.3.8" data-path="joins-and-complex-queries-13.html"><a href="joins-and-complex-queries-13.html#rank-customers-with-highest-open-amounts"><i class="fa fa-check"></i><b>10.3.8</b> Rank customers with highest open amounts</a></li>
<li class="chapter" data-level="10.3.9" data-path="joins-and-complex-queries-13.html"><a href="joins-and-complex-queries-13.html#what-film-has-been-generated-the-most-revenue-assuming-all-amounts-are-collected"><i class="fa fa-check"></i><b>10.3.9</b> what film has been generated the most revenue assuming all amounts are collected</a></li>
<li class="chapter" data-level="10.3.10" data-path="joins-and-complex-queries-13.html"><a href="joins-and-complex-queries-13.html#which-films-are-in-one-store-but-not-the-other."><i class="fa fa-check"></i><b>10.3.10</b> which films are in one store but not the other.</a></li>
<li class="chapter" data-level="10.3.11" data-path="joins-and-complex-queries-13.html"><a href="joins-and-complex-queries-13.html#compute-the-outstanding-balance."><i class="fa fa-check"></i><b>10.3.11</b> Compute the outstanding balance.</a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="joins-and-complex-queries-13.html"><a href="joins-and-complex-queries-13.html#different-strategies-for-interacting-with-the-database"><i class="fa fa-check"></i><b>10.4</b> Different strategies for interacting with the database</a><ul>
<li class="chapter" data-level="10.4.1" data-path="joins-and-complex-queries-13.html"><a href="joins-and-complex-queries-13.html#use-dbgetquery"><i class="fa fa-check"></i><b>10.4.1</b> Use dbGetQuery</a></li>
<li class="chapter" data-level="10.4.2" data-path="joins-and-complex-queries-13.html"><a href="joins-and-complex-queries-13.html#use-dbexecute"><i class="fa fa-check"></i><b>10.4.2</b> Use dbExecute</a></li>
<li class="chapter" data-level="10.4.3" data-path="joins-and-complex-queries-13.html"><a href="joins-and-complex-queries-13.html#anti-join-find-sophie-who-have-never-rented-a-movie."><i class="fa fa-check"></i><b>10.4.3</b> anti join – Find sophie who have never rented a movie.</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="11" data-path="sql-quick-start-simple-retrieval-15.html"><a href="sql-quick-start-simple-retrieval-15.html"><i class="fa fa-check"></i><b>11</b> SQL Quick start - simple retrieval (15)</a><ul>
<li class="chapter" data-level="11.1" data-path="sql-quick-start-simple-retrieval-15.html"><a href="sql-quick-start-simple-retrieval-15.html#databases-and-third-normal-form---3nf"><i class="fa fa-check"></i><b>11.1</b> Databases and Third Normal Form - 3NF</a></li>
<li class="chapter" data-level="11.2" data-path="sql-quick-start-simple-retrieval-15.html"><a href="sql-quick-start-simple-retrieval-15.html#sql-commands"><i class="fa fa-check"></i><b>11.2</b> SQL Commands</a></li>
<li class="chapter" data-level="11.3" data-path="sql-quick-start-simple-retrieval-15.html"><a href="sql-quick-start-simple-retrieval-15.html#sql-select-quick-start"><i class="fa fa-check"></i><b>11.3</b> SQL SELECT Quick Start</a><ul>
<li class="chapter" data-level="11.3.1" data-path="sql-quick-start-simple-retrieval-15.html"><a href="sql-quick-start-simple-retrieval-15.html#select-clause-column-selection-vertical-partioning-of-data"><i class="fa fa-check"></i><b>11.3.1</b> SELECT Clause: Column Selection – Vertical Partioning of Data</a></li>
<li class="chapter" data-level="11.3.2" data-path="sql-quick-start-simple-retrieval-15.html"><a href="sql-quick-start-simple-retrieval-15.html#sql-comments"><i class="fa fa-check"></i><b>11.3.2</b> SQL Comments</a></li>
<li class="chapter" data-level="11.3.3" data-path="sql-quick-start-simple-retrieval-15.html"><a href="sql-quick-start-simple-retrieval-15.html#from-clause"><i class="fa fa-check"></i><b>11.3.3</b> FROM Clause</a></li>
<li class="chapter" data-level="11.3.4" data-path="sql-quick-start-simple-retrieval-15.html"><a href="sql-quick-start-simple-retrieval-15.html#where-clause-row-selection-horizontal-partitioning-of-data"><i class="fa fa-check"></i><b>11.3.4</b> WHERE Clause: Row Selection – Horizontal Partitioning of Data</a></li>
</ul></li>
<li class="chapter" data-level="11.4" data-path="sql-quick-start-simple-retrieval-15.html"><a href="sql-quick-start-simple-retrieval-15.html#paradigm-shift-from-r-dplyr-to-sql"><i class="fa fa-check"></i><b>11.4</b> Paradigm Shift from R-Dplyr to SQL</a><ul>
<li class="chapter" data-level="11.4.1" data-path="sql-quick-start-simple-retrieval-15.html"><a href="sql-quick-start-simple-retrieval-15.html#big-bang-versus-piped-incremental-steps."><i class="fa fa-check"></i><b>11.4.1</b> Big bang versus piped incremental steps.</a></li>
<li class="chapter" data-level="11.4.2" data-path="sql-quick-start-simple-retrieval-15.html"><a href="sql-quick-start-simple-retrieval-15.html#sql-execution-order"><i class="fa fa-check"></i><b>11.4.2</b> SQL Execution Order</a></li>
<li class="chapter" data-level="11.4.3" data-path="sql-quick-start-simple-retrieval-15.html"><a href="sql-quick-start-simple-retrieval-15.html#which-server"><i class="fa fa-check"></i><b>11.4.3</b> Which Server?</a></li>
<li class="chapter" data-level="11.4.4" data-path="sql-quick-start-simple-retrieval-15.html"><a href="sql-quick-start-simple-retrieval-15.html#which-database"><i class="fa fa-check"></i><b>11.4.4</b> Which database?</a></li>
<li class="chapter" data-level="11.4.5" data-path="sql-quick-start-simple-retrieval-15.html"><a href="sql-quick-start-simple-retrieval-15.html#how-do-i-check-for-databases"><i class="fa fa-check"></i><b>11.4.5</b> How do I check for databases?</a></li>
<li class="chapter" data-level="11.4.6" data-path="sql-quick-start-simple-retrieval-15.html"><a href="sql-quick-start-simple-retrieval-15.html#how-do-i-change-my-database-connections"><i class="fa fa-check"></i><b>11.4.6</b> How do I change my database connections</a></li>
<li class="chapter" data-level="11.4.7" data-path="sql-quick-start-simple-retrieval-15.html"><a href="sql-quick-start-simple-retrieval-15.html#sql_be_stinger_01"><i class="fa fa-check"></i><b>11.4.7</b> SQL_BE_STINGER_01:</a></li>
<li class="chapter" data-level="11.4.8" data-path="sql-quick-start-simple-retrieval-15.html"><a href="sql-quick-start-simple-retrieval-15.html#which-schema"><i class="fa fa-check"></i><b>11.4.8</b> Which Schema?</a></li>
</ul></li>
<li class="chapter" data-level="11.5" data-path="sql-quick-start-simple-retrieval-15.html"><a href="sql-quick-start-simple-retrieval-15.html#sql_be_02database-schemas-from-ansi-standard-information_schema.tables"><i class="fa fa-check"></i><b>11.5</b> SQL_BE_02:Database Schemas from ANSI standard INFORMATION_SCHEMA.TABLES</a><ul>
<li class="chapter" data-level="11.5.1" data-path="sql-quick-start-simple-retrieval-15.html"><a href="sql-quick-start-simple-retrieval-15.html#exercises-1"><i class="fa fa-check"></i><b>11.5.1</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="11.6" data-path="sql-quick-start-simple-retrieval-15.html"><a href="sql-quick-start-simple-retrieval-15.html#sql_be_03group-by-no-aggregation-deduplication"><i class="fa fa-check"></i><b>11.6</b> SQL_BE_03:Group By No Aggregation – Deduplication</a></li>
<li class="chapter" data-level="11.7" data-path="sql-quick-start-simple-retrieval-15.html"><a href="sql-quick-start-simple-retrieval-15.html#sql_be_04distinct-list-take-2"><i class="fa fa-check"></i><b>11.7</b> SQL_BE_04:Distinct list take 2</a></li>
<li class="chapter" data-level="11.8" data-path="sql-quick-start-simple-retrieval-15.html"><a href="sql-quick-start-simple-retrieval-15.html#sql_be_05---how-to-drill-down-and-aggregate-at-lower-level"><i class="fa fa-check"></i><b>11.8</b> SQL_BE_05 - How to Drill Down and Aggregate at Lower Level</a></li>
<li class="chapter" data-level="11.9" data-path="sql-quick-start-simple-retrieval-15.html"><a href="sql-quick-start-simple-retrieval-15.html#sql_be_06---how-to-filter-groups"><i class="fa fa-check"></i><b>11.9</b> SQL_BE_06 - How to FILTER GROUPS</a></li>
<li class="chapter" data-level="11.10" data-path="sql-quick-start-simple-retrieval-15.html"><a href="sql-quick-start-simple-retrieval-15.html#sql_be_07---how-to-order-result-set-on-a-single-column"><i class="fa fa-check"></i><b>11.10</b> SQL_BE_07 - HOW to ORDER Result Set on a Single Column</a></li>
<li class="chapter" data-level="11.11" data-path="sql-quick-start-simple-retrieval-15.html"><a href="sql-quick-start-simple-retrieval-15.html#sql_be_08---how-to-order-result-set-on-a-multiple-columns-and-descending-order"><i class="fa fa-check"></i><b>11.11</b> SQL_BE_08 - HOW to ORDER Result Set on a Multiple Columns and Descending Order</a><ul>
<li class="chapter" data-level="11.11.1" data-path="sql-quick-start-simple-retrieval-15.html"><a href="sql-quick-start-simple-retrieval-15.html#table-and-column-data-metadata"><i class="fa fa-check"></i><b>11.11.1</b> Table and Column Data – MetaData</a></li>
</ul></li>
<li class="chapter" data-level="11.12" data-path="sql-quick-start-simple-retrieval-15.html"><a href="sql-quick-start-simple-retrieval-15.html#sql_be_09-looks-for-table-metadata-just-in-the-information_schema."><i class="fa fa-check"></i><b>11.12</b> SQL_BE_09 looks for table metadata just in the information_schema.</a></li>
<li class="chapter" data-level="11.13" data-path="sql-quick-start-simple-retrieval-15.html"><a href="sql-quick-start-simple-retrieval-15.html#sql_be_10-column-metadata"><i class="fa fa-check"></i><b>11.13</b> SQL_BE_10: Column Metadata</a></li>
<li class="chapter" data-level="11.14" data-path="sql-quick-start-simple-retrieval-15.html"><a href="sql-quick-start-simple-retrieval-15.html#sql_be_11-table-and-column-metadata"><i class="fa fa-check"></i><b>11.14</b> SQL_BE_11 Table and Column Metadata</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="sql-be-12-and-or-logical-precedence.html"><a href="sql-be-12-and-or-logical-precedence.html"><i class="fa fa-check"></i><b>12</b> SQL_BE_12 AND OR-Logical Precedence</a></li>
<li class="chapter" data-level="13" data-path="sql-be-13-and-or-logical-precedence.html"><a href="sql-be-13-and-or-logical-precedence.html"><i class="fa fa-check"></i><b>13</b> SQL_BE_13 AND (OR-Logical Precedence)</a><ul>
<li class="chapter" data-level="13.0.1" data-path="sql-be-13-and-or-logical-precedence.html"><a href="sql-be-13-and-or-logical-precedence.html#which-table-or-view"><i class="fa fa-check"></i><b>13.0.1</b> Which Table or View</a></li>
<li class="chapter" data-level="13.1" data-path="sql-be-13-and-or-logical-precedence.html"><a href="sql-be-13-and-or-logical-precedence.html#sql_be_14-union-stacked-sets"><i class="fa fa-check"></i><b>13.1</b> SQL_BE_14 UNION Stacked Sets</a><ul>
<li class="chapter" data-level="13.1.1" data-path="sql-be-13-and-or-logical-precedence.html"><a href="sql-be-13-and-or-logical-precedence.html#sql_be_stinger_02-union-order-by-clause"><i class="fa fa-check"></i><b>13.1.1</b> SQL_BE_STINGER_02 Union Order By Clause</a></li>
</ul></li>
<li class="chapter" data-level="13.2" data-path="sql-be-13-and-or-logical-precedence.html"><a href="sql-be-13-and-or-logical-precedence.html#sql_be_15-union-all"><i class="fa fa-check"></i><b>13.2</b> SQL_BE_15 UNION {ALL}</a><ul>
<li class="chapter" data-level="13.2.1" data-path="sql-be-13-and-or-logical-precedence.html"><a href="sql-be-13-and-or-logical-precedence.html#sql_be_16-except-empty-set"><i class="fa fa-check"></i><b>13.2.1</b> SQL_BE_16 EXCEPT EMPTY set</a></li>
<li class="chapter" data-level="13.2.2" data-path="sql-be-13-and-or-logical-precedence.html"><a href="sql-be-13-and-or-logical-precedence.html#sql_be_17-except-not-empty"><i class="fa fa-check"></i><b>13.2.2</b> SQL_BE_17 EXCEPT NOT EMPTY</a></li>
</ul></li>
<li class="chapter" data-level="13.3" data-path="sql-be-13-and-or-logical-precedence.html"><a href="sql-be-13-and-or-logical-precedence.html#stinger_be_"><i class="fa fa-check"></i><b>13.3</b> STINGER_BE_</a></li>
<li class="chapter" data-level="13.4" data-path="sql-be-13-and-or-logical-precedence.html"><a href="sql-be-13-and-or-logical-precedence.html#sql_be_18-describe-table-script"><i class="fa fa-check"></i><b>13.4</b> SQL_BE_18 Describe Table Script</a></li>
<li class="chapter" data-level="13.5" data-path="sql-be-13-and-or-logical-precedence.html"><a href="sql-be-13-and-or-logical-precedence.html#figure-out-view-and-clean-this-up"><i class="fa fa-check"></i><b>13.5</b> Figure out view and clean this up</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="getting-metadata-about-and-from-the-database-21.html"><a href="getting-metadata-about-and-from-the-database-21.html"><i class="fa fa-check"></i><b>14</b> Getting metadata about and from the database (21)</a><ul>
<li class="chapter" data-level="14.1" data-path="getting-metadata-about-and-from-the-database-21.html"><a href="getting-metadata-about-and-from-the-database-21.html#always-look-at-the-data"><i class="fa fa-check"></i><b>14.1</b> Always <em>look</em> at the data</a><ul>
<li class="chapter" data-level="14.1.1" data-path="getting-metadata-about-and-from-the-database-21.html"><a href="getting-metadata-about-and-from-the-database-21.html#connect-with-people-who-own-generate-or-are-the-subjects-of-the-data"><i class="fa fa-check"></i><b>14.1.1</b> Connect with people who own, generate, or are the subjects of the data</a></li>
<li class="chapter" data-level="14.1.2" data-path="getting-metadata-about-and-from-the-database-21.html"><a href="getting-metadata-about-and-from-the-database-21.html#browse-a-few-rows-of-a-table"><i class="fa fa-check"></i><b>14.1.2</b> Browse a few rows of a table</a></li>
</ul></li>
<li class="chapter" data-level="14.2" data-path="getting-metadata-about-and-from-the-database-21.html"><a href="getting-metadata-about-and-from-the-database-21.html#database-contents-and-structure"><i class="fa fa-check"></i><b>14.2</b> Database contents and structure</a><ul>
<li class="chapter" data-level="14.2.1" data-path="getting-metadata-about-and-from-the-database-21.html"><a href="getting-metadata-about-and-from-the-database-21.html#database-structure"><i class="fa fa-check"></i><b>14.2.1</b> Database structure</a></li>
<li class="chapter" data-level="14.2.2" data-path="getting-metadata-about-and-from-the-database-21.html"><a href="getting-metadata-about-and-from-the-database-21.html#contents-of-the-information_schema"><i class="fa fa-check"></i><b>14.2.2</b> Contents of the <code>information_schema</code></a></li>
<li class="chapter" data-level="14.2.3" data-path="getting-metadata-about-and-from-the-database-21.html"><a href="getting-metadata-about-and-from-the-database-21.html#what-tables-are-in-the-database"><i class="fa fa-check"></i><b>14.2.3</b> What tables are in the database?</a></li>
<li class="chapter" data-level="14.2.4" data-path="getting-metadata-about-and-from-the-database-21.html"><a href="getting-metadata-about-and-from-the-database-21.html#digging-into-the-information_schema"><i class="fa fa-check"></i><b>14.2.4</b> Digging into the <code>information_schema</code></a></li>
</ul></li>
<li class="chapter" data-level="14.3" data-path="getting-metadata-about-and-from-the-database-21.html"><a href="getting-metadata-about-and-from-the-database-21.html#what-columns-do-those-tables-contain"><i class="fa fa-check"></i><b>14.3</b> What columns do those tables contain?</a><ul>
<li class="chapter" data-level="14.3.1" data-path="getting-metadata-about-and-from-the-database-21.html"><a href="getting-metadata-about-and-from-the-database-21.html#what-is-the-difference-between-a-view-and-a-base-table"><i class="fa fa-check"></i><b>14.3.1</b> What is the difference between a <code>VIEW</code> and a <code>BASE TABLE</code>?</a></li>
<li class="chapter" data-level="14.3.2" data-path="getting-metadata-about-and-from-the-database-21.html"><a href="getting-metadata-about-and-from-the-database-21.html#what-data-types-are-found-in-the-database"><i class="fa fa-check"></i><b>14.3.2</b> What data types are found in the database?</a></li>
</ul></li>
<li class="chapter" data-level="14.4" data-path="getting-metadata-about-and-from-the-database-21.html"><a href="getting-metadata-about-and-from-the-database-21.html#characterizing-how-things-are-named"><i class="fa fa-check"></i><b>14.4</b> Characterizing how things are named</a><ul>
<li class="chapter" data-level="14.4.1" data-path="getting-metadata-about-and-from-the-database-21.html"><a href="getting-metadata-about-and-from-the-database-21.html#counting-columns-and-name-reuse"><i class="fa fa-check"></i><b>14.4.1</b> Counting columns and name reuse</a></li>
</ul></li>
<li class="chapter" data-level="14.5" data-path="getting-metadata-about-and-from-the-database-21.html"><a href="getting-metadata-about-and-from-the-database-21.html#database-keys"><i class="fa fa-check"></i><b>14.5</b> Database keys</a><ul>
<li class="chapter" data-level="14.5.1" data-path="getting-metadata-about-and-from-the-database-21.html"><a href="getting-metadata-about-and-from-the-database-21.html#direct-sql"><i class="fa fa-check"></i><b>14.5.1</b> Direct SQL</a></li>
<li class="chapter" data-level="14.5.2" data-path="getting-metadata-about-and-from-the-database-21.html"><a href="getting-metadata-about-and-from-the-database-21.html#database-keys-with-dplyr"><i class="fa fa-check"></i><b>14.5.2</b> Database keys with dplyr</a></li>
</ul></li>
<li class="chapter" data-level="14.6" data-path="getting-metadata-about-and-from-the-database-21.html"><a href="getting-metadata-about-and-from-the-database-21.html#creating-your-own-data-dictionary"><i class="fa fa-check"></i><b>14.6</b> Creating your own data dictionary</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="drilling-into-your-db-environment-22.html"><a href="drilling-into-your-db-environment-22.html"><i class="fa fa-check"></i><b>15</b> Drilling into Your DB Environment (22)</a><ul>
<li class="chapter" data-level="15.1" data-path="drilling-into-your-db-environment-22.html"><a href="drilling-into-your-db-environment-22.html#which-database-1"><i class="fa fa-check"></i><b>15.1</b> Which database?</a></li>
<li class="chapter" data-level="15.2" data-path="drilling-into-your-db-environment-22.html"><a href="drilling-into-your-db-environment-22.html#how-many-databases-reside-in-the-docker-container"><i class="fa fa-check"></i><b>15.2</b> How many databases reside in the Docker Container?</a></li>
<li class="chapter" data-level="15.3" data-path="drilling-into-your-db-environment-22.html"><a href="drilling-into-your-db-environment-22.html#which-schema-1"><i class="fa fa-check"></i><b>15.3</b> Which Schema?</a></li>
<li class="chapter" data-level="15.4" data-path="drilling-into-your-db-environment-22.html"><a href="drilling-into-your-db-environment-22.html#exercises-2"><i class="fa fa-check"></i><b>15.4</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="16" data-path="explain-queries-71.html"><a href="explain-queries-71.html"><i class="fa fa-check"></i><b>16</b> Explain queries (71)</a><ul>
<li class="chapter" data-level="16.1" data-path="explain-queries-71.html"><a href="explain-queries-71.html#performance-considerations"><i class="fa fa-check"></i><b>16.1</b> Performance considerations</a></li>
<li class="chapter" data-level="16.2" data-path="explain-queries-71.html"><a href="explain-queries-71.html#clean-up-1"><i class="fa fa-check"></i><b>16.2</b> Clean up</a></li>
</ul></li>
<li class="chapter" data-level="17" data-path="sql-queries-behind-the-scenes-72.html"><a href="sql-queries-behind-the-scenes-72.html"><i class="fa fa-check"></i><b>17</b> SQL queries behind the scenes (72)</a><ul>
<li class="chapter" data-level="17.1" data-path="sql-queries-behind-the-scenes-72.html"><a href="sql-queries-behind-the-scenes-72.html#sql-execution-steps"><i class="fa fa-check"></i><b>17.1</b> SQL Execution Steps</a></li>
<li class="chapter" data-level="17.2" data-path="sql-queries-behind-the-scenes-72.html"><a href="sql-queries-behind-the-scenes-72.html#passing-values-to-sql-statements"><i class="fa fa-check"></i><b>17.2</b> Passing values to SQL statements</a></li>
<li class="chapter" data-level="17.3" data-path="sql-queries-behind-the-scenes-72.html"><a href="sql-queries-behind-the-scenes-72.html#pass-multiple-sets-of-values-with-dbbind"><i class="fa fa-check"></i><b>17.3</b> Pass multiple sets of values with dbBind():</a></li>
<li class="chapter" data-level="17.4" data-path="sql-queries-behind-the-scenes-72.html"><a href="sql-queries-behind-the-scenes-72.html#clean-up-2"><i class="fa fa-check"></i><b>17.4</b> Clean up</a></li>
</ul></li>
<li class="chapter" data-level="18" data-path="writing-to-the-dbms-73.html"><a href="writing-to-the-dbms-73.html"><i class="fa fa-check"></i><b>18</b> Writing to the DBMS (73)</a><ul>
<li class="chapter" data-level="18.1" data-path="writing-to-the-dbms-73.html"><a href="writing-to-the-dbms-73.html#create-a-new-table"><i class="fa fa-check"></i><b>18.1</b> Create a new table</a></li>
<li class="chapter" data-level="18.2" data-path="writing-to-the-dbms-73.html"><a href="writing-to-the-dbms-73.html#modify-an-existing-table"><i class="fa fa-check"></i><b>18.2</b> Modify an existing table</a></li>
<li class="chapter" data-level="18.3" data-path="writing-to-the-dbms-73.html"><a href="writing-to-the-dbms-73.html#remove-table-and-clean-up"><i class="fa fa-check"></i><b>18.3</b> Remove table and Clean up</a></li>
</ul></li>
<li class="chapter" data-level="19" data-path="appendix-appendix-a-other-resources-89.html"><a href="appendix-appendix-a-other-resources-89.html"><i class="fa fa-check"></i><b>19</b> (APPENDIX) Appendix A: Other resources (89)</a><ul>
<li class="chapter" data-level="19.1" data-path="appendix-appendix-a-other-resources-89.html"><a href="appendix-appendix-a-other-resources-89.html#editing-this-book"><i class="fa fa-check"></i><b>19.1</b> Editing this book</a></li>
<li class="chapter" data-level="19.2" data-path="appendix-appendix-a-other-resources-89.html"><a href="appendix-appendix-a-other-resources-89.html#docker-alternatives"><i class="fa fa-check"></i><b>19.2</b> Docker alternatives</a></li>
<li class="chapter" data-level="19.3" data-path="appendix-appendix-a-other-resources-89.html"><a href="appendix-appendix-a-other-resources-89.html#docker-and-r"><i class="fa fa-check"></i><b>19.3</b> Docker and R</a></li>
<li class="chapter" data-level="19.4" data-path="appendix-appendix-a-other-resources-89.html"><a href="appendix-appendix-a-other-resources-89.html#documentation-for-docker-and-postgres"><i class="fa fa-check"></i><b>19.4</b> Documentation for Docker and Postgres</a></li>
<li class="chapter" data-level="19.5" data-path="appendix-appendix-a-other-resources-89.html"><a href="appendix-appendix-a-other-resources-89.html#sql-and-dplyr"><i class="fa fa-check"></i><b>19.5</b> SQL and dplyr</a></li>
<li class="chapter" data-level="19.6" data-path="appendix-appendix-a-other-resources-89.html"><a href="appendix-appendix-a-other-resources-89.html#more-resources"><i class="fa fa-check"></i><b>19.6</b> More Resources</a></li>
</ul></li>
<li class="chapter" data-level="20" data-path="appendix-b-mapping-your-local-environment-92.html"><a href="appendix-b-mapping-your-local-environment-92.html"><i class="fa fa-check"></i><b>20</b> APPENDIX B - Mapping your local environment (92)</a><ul>
<li class="chapter" data-level="20.1" data-path="appendix-b-mapping-your-local-environment-92.html"><a href="appendix-b-mapping-your-local-environment-92.html#environment-tools-used-in-this-chapter"><i class="fa fa-check"></i><b>20.1</b> Environment Tools Used in this Chapter</a></li>
<li class="chapter" data-level="20.2" data-path="appendix-b-mapping-your-local-environment-92.html"><a href="appendix-b-mapping-your-local-environment-92.html#communicating-with-docker-applications-1"><i class="fa fa-check"></i><b>20.2</b> Communicating with Docker Applications</a></li>
</ul></li>
<li class="chapter" data-level="21" data-path="appendix-c-creating-the-sql-pet-docker-container-a-step-at-a-time.html"><a href="appendix-c-creating-the-sql-pet-docker-container-a-step-at-a-time.html"><i class="fa fa-check"></i><b>21</b> APPENDIX C - Creating the sql-pet Docker container a step at a time</a><ul>
<li class="chapter" data-level="21.1" data-path="appendix-c-creating-the-sql-pet-docker-container-a-step-at-a-time.html"><a href="appendix-c-creating-the-sql-pet-docker-container-a-step-at-a-time.html#overview-1"><i class="fa fa-check"></i><b>21.1</b> Overview</a></li>
<li class="chapter" data-level="21.2" data-path="appendix-c-creating-the-sql-pet-docker-container-a-step-at-a-time.html"><a href="appendix-c-creating-the-sql-pet-docker-container-a-step-at-a-time.html#download-the-dvdrental-backup-file"><i class="fa fa-check"></i><b>21.2</b> Download the <code>dvdrental</code> backup file</a></li>
<li class="chapter" data-level="21.3" data-path="appendix-c-creating-the-sql-pet-docker-container-a-step-at-a-time.html"><a href="appendix-c-creating-the-sql-pet-docker-container-a-step-at-a-time.html#build-the-docker-container"><i class="fa fa-check"></i><b>21.3</b> Build the Docker Container</a></li>
<li class="chapter" data-level="21.4" data-path="appendix-c-creating-the-sql-pet-docker-container-a-step-at-a-time.html"><a href="appendix-c-creating-the-sql-pet-docker-container-a-step-at-a-time.html#create-the-database-and-restore-from-the-backup"><i class="fa fa-check"></i><b>21.4</b> Create the database and restore from the backup</a></li>
<li class="chapter" data-level="21.5" data-path="appendix-c-creating-the-sql-pet-docker-container-a-step-at-a-time.html"><a href="appendix-c-creating-the-sql-pet-docker-container-a-step-at-a-time.html#connect-to-the-database-with-r"><i class="fa fa-check"></i><b>21.5</b> Connect to the database with R</a></li>
<li class="chapter" data-level="21.6" data-path="appendix-c-creating-the-sql-pet-docker-container-a-step-at-a-time.html"><a href="appendix-c-creating-the-sql-pet-docker-container-a-step-at-a-time.html#cleaning-up-1"><i class="fa fa-check"></i><b>21.6</b> Cleaning up</a></li>
</ul></li>
<li class="chapter" data-level="22" data-path="appendix-d-quick-guide-to-sql-94.html"><a href="appendix-d-quick-guide-to-sql-94.html"><i class="fa fa-check"></i><b>22</b> APPENDIX D - Quick Guide to SQL (94)</a><ul>
<li class="chapter" data-level="22.1" data-path="appendix-d-quick-guide-to-sql-94.html"><a href="appendix-d-quick-guide-to-sql-94.html#small-architecture"><i class="fa fa-check"></i><b>22.1</b> Small architecture</a></li>
<li class="chapter" data-level="22.2" data-path="appendix-d-quick-guide-to-sql-94.html"><a href="appendix-d-quick-guide-to-sql-94.html#medium-architecture"><i class="fa fa-check"></i><b>22.2</b> Medium architecture</a></li>
<li class="chapter" data-level="22.3" data-path="appendix-d-quick-guide-to-sql-94.html"><a href="appendix-d-quick-guide-to-sql-94.html#large-architecture-95"><i class="fa fa-check"></i><b>22.3</b> Large architecture (95)</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">R, Databases and Docker</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="sql-quick-start---simple-retrieval-15" class="section level1">
<h1><span class="header-section-number">Chapter 11</span> SQL Quick start - simple retrieval (15)</h1>
<p>Start up the <code>docker-pet</code> container</p>
<div class="sourceCode" id="cb141"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb141-1" data-line-number="1"><span class="kw">sp_docker_start</span>(<span class="st">&quot;sql-pet&quot;</span>)</a></code></pre></div>
<p>Now connect to the <code>dvdrental</code> database with R</p>
<div class="sourceCode" id="cb142"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb142-1" data-line-number="1">con &lt;-<span class="st"> </span><span class="kw">sp_get_postgres_connection</span>(</a>
<a class="sourceLine" id="cb142-2" data-line-number="2">  <span class="dt">user =</span> <span class="kw">Sys.getenv</span>(<span class="st">&quot;DEFAULT_POSTGRES_USER_NAME&quot;</span>),</a>
<a class="sourceLine" id="cb142-3" data-line-number="3">  <span class="dt">password =</span>  <span class="kw">Sys.getenv</span>(<span class="st">&quot;DEFAULT_POSTGRES_PASSWORD&quot;</span>),</a>
<a class="sourceLine" id="cb142-4" data-line-number="4">  <span class="dt">dbname =</span> <span class="st">&quot;dvdrental&quot;</span>,</a>
<a class="sourceLine" id="cb142-5" data-line-number="5">  <span class="dt">seconds_to_test =</span> <span class="dv">10</span>)</a>
<a class="sourceLine" id="cb142-6" data-line-number="6">con</a></code></pre></div>
<pre><code>## &lt;PqConnection&gt; dvdrental@localhost:5432</code></pre>
<div class="sourceCode" id="cb144"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb144-1" data-line-number="1">colFmt &lt;-<span class="st"> </span><span class="cf">function</span>(x,color)</a>
<a class="sourceLine" id="cb144-2" data-line-number="2">{</a>
<a class="sourceLine" id="cb144-3" data-line-number="3">  <span class="co"># x string</span></a>
<a class="sourceLine" id="cb144-4" data-line-number="4">  <span class="co"># color </span></a>
<a class="sourceLine" id="cb144-5" data-line-number="5">  outputFormat =<span class="st"> </span>knitr<span class="op">::</span>opts_knit<span class="op">$</span><span class="kw">get</span>(<span class="st">&quot;rmarkdown.pandoc.to&quot;</span>)</a>
<a class="sourceLine" id="cb144-6" data-line-number="6">  <span class="cf">if</span>(outputFormat <span class="op">==</span><span class="st"> &#39;latex&#39;</span>)</a>
<a class="sourceLine" id="cb144-7" data-line-number="7">    <span class="kw">paste</span>(<span class="st">&quot;</span><span class="ch">\\</span><span class="st">textcolor{&quot;</span>,color,<span class="st">&quot;}{&quot;</span>,x,<span class="st">&quot;}&quot;</span>,<span class="dt">sep=</span><span class="st">&quot;&quot;</span>)</a>
<a class="sourceLine" id="cb144-8" data-line-number="8">  <span class="cf">else</span> <span class="cf">if</span>(outputFormat <span class="op">==</span><span class="st"> &#39;html&#39;</span>)</a>
<a class="sourceLine" id="cb144-9" data-line-number="9">    <span class="kw">paste</span>(<span class="st">&quot;&lt;font color=&#39;&quot;</span>,color,<span class="st">&quot;&#39;&gt;&quot;</span>,x,<span class="st">&quot;&lt;/font&gt;&quot;</span>,<span class="dt">sep=</span><span class="st">&quot;&quot;</span>)</a>
<a class="sourceLine" id="cb144-10" data-line-number="10">  <span class="cf">else</span></a>
<a class="sourceLine" id="cb144-11" data-line-number="11">    x</a>
<a class="sourceLine" id="cb144-12" data-line-number="12">}</a>
<a class="sourceLine" id="cb144-13" data-line-number="13"></a>
<a class="sourceLine" id="cb144-14" data-line-number="14"><span class="co"># sample call</span></a>
<a class="sourceLine" id="cb144-15" data-line-number="15"><span class="co"># * `r colFmt(&#39;Cover inline tables in future section&#39;,&#39;red&#39;)`</span></a></code></pre></div>
<p>Moved this from 11-elementary-queries</p>
<div class="sourceCode" id="cb145"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb145-1" data-line-number="1">dplyr_summary_df &lt;-</a>
<a class="sourceLine" id="cb145-2" data-line-number="2"><span class="st">    </span><span class="kw">read.delim</span>(</a>
<a class="sourceLine" id="cb145-3" data-line-number="3">    <span class="st">&#39;11-dplyr_sql_summary_table.tsv&#39;</span>,</a>
<a class="sourceLine" id="cb145-4" data-line-number="4">    <span class="dt">header =</span> <span class="ot">TRUE</span>,</a>
<a class="sourceLine" id="cb145-5" data-line-number="5">    <span class="dt">sep =</span> <span class="st">&#39;</span><span class="ch">\t</span><span class="st">&#39;</span>,</a>
<a class="sourceLine" id="cb145-6" data-line-number="6">    <span class="dt">as.is =</span> <span class="ot">TRUE</span></a>
<a class="sourceLine" id="cb145-7" data-line-number="7">    )</a>
<a class="sourceLine" id="cb145-8" data-line-number="8"></a>
<a class="sourceLine" id="cb145-9" data-line-number="9"><span class="kw">head</span>(dplyr_summary_df)</a></code></pre></div>
<pre><code>##   In          Dplyr_Function
## 1  Y               arrange()
## 2 Y?              distinct()
## 3  Y       select() rename()
## 4  N                  pull()
## 5  Y    mutate() transmute()
## 6  Y summarise() summarize()
##                                      description
## 1                      Arrange rows by variables
## 2           Return rows with matching conditions
## 3                Select/rename variables by name
## 4                     Pull out a single variable
## 5                              Add new variables
## 6 Reduces multiple values down to a single value
##                            SQL_Clause Notes                 Category
## 1                            ORDER BY    NA Basic single-table verbs
## 2                   SELECT distinct *    NA Basic single-table verbs
## 3       SELECT column_name alias_name    NA Basic single-table verbs
## 4                 SELECT column_name;    NA Basic single-table verbs
## 5 SELECT computed_value computed_name    NA Basic single-table verbs
## 6 SELECT aggregate_functions GROUP BY    NA Basic single-table verbs</code></pre>
<div id="databases-and-third-normal-form---3nf" class="section level2">
<h2><span class="header-section-number">11.1</span> Databases and Third Normal Form - 3NF</h2>
<p>Most relational database applications are designed to be third normal form “like”, 3NF. The key benefits of 3NF are</p>
<ol style="list-style-type: decimal">
<li>speedy on-line transactional processing, OLTP.</li>
<li>improved referential integrity, reduce modification anomalies that can occur during an insert, update, or delete operation.</li>
<li>reduced storage, elimination of redundant data.</li>
</ol>
<p>3NF is great for database application input performance, but not so great for getting the data back out for the data analyst or report writer. As a data analyst, you might get the ubiquitous Excel spreadsheet with all the information needed to start an Exploratory Data Analysis, EDA. The spreadsheet may have provider, patient, diagnosis, procedure, and insurance information all “neatly” arranged on a single row. At least “neatly” when compared to the same information stored in the database, in at least 5 tables.</p>
<p>For this tutorial, the most important thing to know about 3NF is that the data you are looking for gets spread across many many tables. Working in a relational database requires you to</p>
<ol style="list-style-type: decimal">
<li>find the many many different tables that contains your data.<br />
</li>
<li>Understand the relationships that tie the tables together correctly to ensure that data is not dropped or duplicated. Data that is dropped or duplicated can either over or understate your aggregated numeric values.</li>
</ol>
<div class="figure">
<img src="ERD_Hospital_Billing_System.PNG" alt="hospital-billing-erd" />
<p class="caption">hospital-billing-erd</p>
</div>
<p><a href="https://www.smartdraw.com/entity-relationship-diagram/examples/hospital-billing-entity-relationship-diagram/" class="uri">https://www.smartdraw.com/entity-relationship-diagram/examples/hospital-billing-entity-relationship-diagram/</a></p>
<p>Real life applications have 100’s or even 1000’s of tables supporting the application. The goal is to transform the application data model into a useful data analysis model using the DDL and DML SQL statements.</p>
</div>
<div id="sql-commands" class="section level2">
<h2><span class="header-section-number">11.2</span> SQL Commands</h2>
<p>SQL commands fall into four categories.</p>
<table>
<colgroup>
<col width="20%" />
<col width="79%" />
</colgroup>
<thead>
<tr class="header">
<th>SQL Category</th>
<th>Definition</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>DDL:Data Definition Language</td>
<td>DBA’s execute these commands to define objects in the database.</td>
</tr>
<tr class="even">
<td>DML:Data Manipulation Language</td>
<td>Users and developers execute these commands to investigate data.</td>
</tr>
<tr class="odd">
<td>DCL:Data Control Language</td>
<td>DBA’s execute these commands to grant/revoke access to</td>
</tr>
<tr class="even">
<td>TCL:Transaction Control Language</td>
<td>Developers execute these commands when developing applications.</td>
</tr>
</tbody>
</table>
<p>Data analysts use the SELECT DML command to learn interesting things about the data stored in the database. Applications are used to control the insert, update, and deletion of data in the database. Data users can update the database objects via the application which enforces referential integrity in the database. Data users should never directly update data application database objects. Leave this task to the developers and DBA’s.</p>
<p>DBA’s can setup a sandbox within the database for a data analyst. The application(s) do not maintain the data in the sandbox.</p>
<p>The <code>sql-pet</code> database is tiny, but for the purposes of these exercises, we assume that data so large that it will not easily fit into the memory of your laptop.</p>
<p>This tutorial focuses on the most frequently used SQL statement, the SQL SELECT statement.</p>
<p>A SQL SELECT statement consists of 1 to 6 clauses.</p>
<table>
<colgroup>
<col width="26%" />
<col width="26%" />
<col width="46%" />
</colgroup>
<thead>
<tr class="header">
<th>SQL Clause</th>
<th>DPLYR Verb</th>
<th>SQL Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>SELECT</td>
<td>SELECT()</td>
<td>Contains a list of column names from an object or a derived value.</td>
</tr>
<tr class="even">
<td></td>
<td>mutate()</td>
<td></td>
</tr>
<tr class="odd">
<td>FROM</td>
<td></td>
<td>Contains a list of related tables from which the SELECT list of columns is derived.</td>
</tr>
<tr class="even">
<td>WHERE</td>
<td>filter()</td>
<td>Provides the filter conditions the objects in the FROM clause must meet.</td>
</tr>
<tr class="odd">
<td>GROUP BY</td>
<td>group_by()</td>
<td>Contains a list rollup aggregation columns.</td>
</tr>
<tr class="even">
<td>HAVING</td>
<td></td>
<td>Provides the filter condition on the the GROUP BY clause.</td>
</tr>
<tr class="odd">
<td>ORDER BY</td>
<td>arrange()</td>
<td>Contains a list of column names indicating the order of the column value. Each column can be either ASCending or DEScending.</td>
</tr>
</tbody>
</table>
<p>The foundation of the SQL language is based set theory and the result of a SQL SELECT statement is referred to as a result set. A SQL SELECT statement is “guaranteed” to return the same set of data,
but not necessarily in the same order. However, in practice, the result set is usually in the same order.</p>
<p>SQL SELECT statements can be broken up into two categories, SELECT detail statements and SELECT aggregate statements.</p>
<table>
<thead>
<tr class="header">
<th>SELECT DETAIL</th>
<th>SELECT AGGREGATE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>select det_col1…det_coln</td>
<td>select det_agg1…, agg1,…,aggn</td>
</tr>
<tr class="even">
<td>from same</td>
<td>from same</td>
</tr>
<tr class="odd">
<td>where same</td>
<td>where same</td>
</tr>
<tr class="even">
<td></td>
<td>group by det_agg1</td>
</tr>
<tr class="odd">
<td></td>
<td>having <aggregation condition></td>
</tr>
<tr class="even">
<td>order by same</td>
<td>order by same</td>
</tr>
</tbody>
</table>
<p>The difference between the two statements is the AGGREGATE has</p>
<ol style="list-style-type: decimal">
<li>select clause has one or more detail columns, det_agg1…, on which values get aggregated against/rolled up to.</li>
<li>select clause zero or more aggregated values, agg1, …, aggn</li>
<li>group by clause is required and matches the one or more detail columns, det_agg1.</li>
<li>having clause is optional and adds a filter condition on one or more agg1 … aggn values.</li>
</ol>
</div>
<div id="sql-select-quick-start" class="section level2">
<h2><span class="header-section-number">11.3</span> SQL SELECT Quick Start</h2>
<p>This section focuses on getting new SQL users familiar with the six SQL query clauses and a single table. SQL queries from multiple tables are discussed in the JOIN section of this tutorial. The JOIN section resolves the issue introduced with 3NF, the splitting of data into many many tables, back into a denormalaized format similar to the Excel spreadsheet.</p>
<p>The DBI::dbGetQuery function is used to submit SQL SELECT statements to the Postgres database. At a minimum it requires two parameters, a connection object and a SQL SELECT statement.</p>
<p>In the following section we only look at SELECT DETAIL statements.</p>
<div id="select-clause-column-selection-vertical-partioning-of-data" class="section level3">
<h3><span class="header-section-number">11.3.1</span> SELECT Clause: Column Selection – Vertical Partioning of Data</h3>
<div id="simplest-sql-query-all-rows-and-all-columns-from-a-single-table." class="section level4">
<h4><span class="header-section-number">11.3.1.1</span> 1. Simplest SQL query: All rows and all columns from a single table.</h4>
<div class="sourceCode" id="cb147"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb147-1" data-line-number="1">rs &lt;-</a>
<a class="sourceLine" id="cb147-2" data-line-number="2"><span class="st">  </span>DBI<span class="op">::</span><span class="kw">dbGetQuery</span>(</a>
<a class="sourceLine" id="cb147-3" data-line-number="3">  con,</a>
<a class="sourceLine" id="cb147-4" data-line-number="4">  <span class="st">&quot;</span></a>
<a class="sourceLine" id="cb147-5" data-line-number="5"><span class="st">  select * from store;</span></a>
<a class="sourceLine" id="cb147-6" data-line-number="6"><span class="st">  &quot;</span>)</a>
<a class="sourceLine" id="cb147-7" data-line-number="7"><span class="kw">kable</span>(rs,<span class="dt">caption =</span> <span class="st">&#39;select all columns&#39;</span>)  </a></code></pre></div>
<table>
<caption><span id="tab:unnamed-chunk-5">Table 11.1: </span>select all columns</caption>
<thead>
<tr class="header">
<th align="right">store_id</th>
<th align="right">manager_staff_id</th>
<th align="right">address_id</th>
<th align="left">last_update</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">1</td>
<td align="right">1</td>
<td align="right">1</td>
<td align="left">2006-02-15 09:57:12</td>
</tr>
<tr class="even">
<td align="right">2</td>
<td align="right">2</td>
<td align="right">2</td>
<td align="left">2006-02-15 09:57:12</td>
</tr>
</tbody>
</table>
</div>
<div id="same-query-as-1-but-only-show-first-two-columns" class="section level4">
<h4><span class="header-section-number">11.3.1.2</span> 2. Same Query as 1, but only show first two columns;</h4>
<div class="sourceCode" id="cb148"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb148-1" data-line-number="1">rs &lt;-</a>
<a class="sourceLine" id="cb148-2" data-line-number="2"><span class="st">  </span>DBI<span class="op">::</span><span class="kw">dbGetQuery</span>(</a>
<a class="sourceLine" id="cb148-3" data-line-number="3">  con,</a>
<a class="sourceLine" id="cb148-4" data-line-number="4">  <span class="st">&quot;</span></a>
<a class="sourceLine" id="cb148-5" data-line-number="5"><span class="st">  select STORE_ID, manager_staff_id from store;  </span></a>
<a class="sourceLine" id="cb148-6" data-line-number="6"><span class="st">  &quot;</span>)</a>
<a class="sourceLine" id="cb148-7" data-line-number="7"><span class="kw">kable</span>(rs,<span class="dt">caption =</span> <span class="st">&#39;select first two columns only&#39;</span>) </a></code></pre></div>
<table>
<caption><span id="tab:unnamed-chunk-6">Table 11.2: </span>select first two columns only</caption>
<thead>
<tr class="header">
<th align="right">store_id</th>
<th align="right">manager_staff_id</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">1</td>
<td align="right">1</td>
</tr>
<tr class="even">
<td align="right">2</td>
<td align="right">2</td>
</tr>
</tbody>
</table>
</div>
<div id="same-query-as-2-but-reverse-the-column-order" class="section level4">
<h4><span class="header-section-number">11.3.1.3</span> 3. Same Query as 2, but reverse the column order</h4>
<p>dvdrental=# select manager_staff_id,store_id from store;</p>
<div class="sourceCode" id="cb149"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb149-1" data-line-number="1">rs &lt;-</a>
<a class="sourceLine" id="cb149-2" data-line-number="2"><span class="st">  </span>DBI<span class="op">::</span><span class="kw">dbGetQuery</span>(</a>
<a class="sourceLine" id="cb149-3" data-line-number="3">  con,</a>
<a class="sourceLine" id="cb149-4" data-line-number="4">  <span class="st">&quot;</span></a>
<a class="sourceLine" id="cb149-5" data-line-number="5"><span class="st">  select manager_staff_id,store_id from store;  </span></a>
<a class="sourceLine" id="cb149-6" data-line-number="6"><span class="st">  &quot;</span>)</a>
<a class="sourceLine" id="cb149-7" data-line-number="7"><span class="kw">kable</span>(rs,<span class="dt">caption =</span> <span class="st">&#39;reverse the column order&#39;</span>) </a></code></pre></div>
<table>
<caption><span id="tab:unnamed-chunk-7">Table 11.3: </span>reverse the column order</caption>
<thead>
<tr class="header">
<th align="right">manager_staff_id</th>
<th align="right">store_id</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">1</td>
<td align="right">1</td>
</tr>
<tr class="even">
<td align="right">2</td>
<td align="right">2</td>
</tr>
</tbody>
</table>
</div>
<div id="rename-columns-sql-column-alias-in-the-result-set" class="section level4">
<h4><span class="header-section-number">11.3.1.4</span> 4. Rename Columns – SQL column alias in the result set</h4>
<div class="sourceCode" id="cb150"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb150-1" data-line-number="1">rs &lt;-</a>
<a class="sourceLine" id="cb150-2" data-line-number="2"><span class="st">  </span>DBI<span class="op">::</span><span class="kw">dbGetQuery</span>(</a>
<a class="sourceLine" id="cb150-3" data-line-number="3">  con,</a>
<a class="sourceLine" id="cb150-4" data-line-number="4">  <span class="st">&quot;</span></a>
<a class="sourceLine" id="cb150-5" data-line-number="5"><span class="st">  select manager_staff_id mgr_sid,store_id st_id from store;    </span></a>
<a class="sourceLine" id="cb150-6" data-line-number="6"><span class="st">  &quot;</span>)</a>
<a class="sourceLine" id="cb150-7" data-line-number="7"><span class="kw">kable</span>(rs,<span class="dt">caption =</span> <span class="st">&#39;Rename Columns&#39;</span>) </a></code></pre></div>
<table>
<caption><span id="tab:unnamed-chunk-8">Table 11.4: </span>Rename Columns</caption>
<thead>
<tr class="header">
<th align="right">mgr_sid</th>
<th align="right">st_id</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">1</td>
<td align="right">1</td>
</tr>
<tr class="even">
<td align="right">2</td>
<td align="right">2</td>
</tr>
</tbody>
</table>
<pre><code>The manager_staff_id has changed to mgr_sid.
store_id has changed to st_id.  

Note that the column names have changed in the result set only, not in the actual database table.  
The DBA&#39;s will not allow a space or other special characters in a database table column name.  

Some motivations for aliasing the result set column names are

  1.  Some database table column names are not user friendly.
  2.  When multiple tables are joined, the column names may be the same in one or more tables and one needs to distinguish between the column names from the different tables.
  </code></pre>
</div>
<div id="adding-meta-data-columns-to-the-result-set" class="section level4">
<h4><span class="header-section-number">11.3.1.5</span> 5. Adding Meta Data Columns to the Result Set</h4>
<div class="sourceCode" id="cb152"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb152-1" data-line-number="1">rs &lt;-</a>
<a class="sourceLine" id="cb152-2" data-line-number="2"><span class="st">  </span>DBI<span class="op">::</span><span class="kw">dbGetQuery</span>(</a>
<a class="sourceLine" id="cb152-3" data-line-number="3">  con,</a>
<a class="sourceLine" id="cb152-4" data-line-number="4">  <span class="st">&quot;</span></a>
<a class="sourceLine" id="cb152-5" data-line-number="5"><span class="st">  select &#39;derived column&#39; showing</span></a>
<a class="sourceLine" id="cb152-6" data-line-number="6"><span class="st">        ,*</span></a>
<a class="sourceLine" id="cb152-7" data-line-number="7"><span class="st">        ,current_database() db</span></a>
<a class="sourceLine" id="cb152-8" data-line-number="8"><span class="st">        ,user</span></a>
<a class="sourceLine" id="cb152-9" data-line-number="9"><span class="st">        ,to_char(now(),&#39;YYYY/MM/DD HH24:MI:SS&#39;) dtts </span></a>
<a class="sourceLine" id="cb152-10" data-line-number="10"><span class="st">    from store;    </span></a>
<a class="sourceLine" id="cb152-11" data-line-number="11"><span class="st">  &quot;</span>)</a>
<a class="sourceLine" id="cb152-12" data-line-number="12"><span class="kw">kable</span>(rs,<span class="dt">caption =</span> <span class="st">&#39;Adding Meta Data Columns&#39;</span>) </a></code></pre></div>
<table>
<caption><span id="tab:unnamed-chunk-9">Table 11.5: </span>Adding Meta Data Columns</caption>
<thead>
<tr class="header">
<th align="left">showing</th>
<th align="right">store_id</th>
<th align="right">manager_staff_id</th>
<th align="right">address_id</th>
<th align="left">last_update</th>
<th align="left">db</th>
<th align="left">user</th>
<th align="left">dtts</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">derived column</td>
<td align="right">1</td>
<td align="right">1</td>
<td align="right">1</td>
<td align="left">2006-02-15 09:57:12</td>
<td align="left">dvdrental</td>
<td align="left">postgres</td>
<td align="left">2018/10/26 19:29:32</td>
</tr>
<tr class="even">
<td align="left">derived column</td>
<td align="right">2</td>
<td align="right">2</td>
<td align="right">2</td>
<td align="left">2006-02-15 09:57:12</td>
<td align="left">dvdrental</td>
<td align="left">postgres</td>
<td align="left">2018/10/26 19:29:32</td>
</tr>
</tbody>
</table>
<pre><code>All the previous examples easily fit on a single line.  This one is longer.  Each column is entered on its own line, indented past the select keyword, and preceeded by a comma.  

1.  The showing column is a hard coded string surrounded by single quotes.  Note that single quotes are for hard coded values and double quotes are for column aliases.  
2.  The db and dtts, date timestamp, are new columns generated from Postgres System Information Functions.
3.  Note that `user` is not a function call, no parenthesis.  </code></pre>
</div>
</div>
<div id="sql-comments" class="section level3">
<h3><span class="header-section-number">11.3.2</span> SQL Comments</h3>
<p>SQL supports both a single line comment, preceed the line with two dashes, <code>--</code>, and a C like block comment, \* … */.</p>
<div id="single-line-comment" class="section level4">
<h4><span class="header-section-number">11.3.2.1</span> 6. Single line comment –</h4>
<div class="sourceCode" id="cb154"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb154-1" data-line-number="1">rs &lt;-</a>
<a class="sourceLine" id="cb154-2" data-line-number="2"><span class="st">  </span>DBI<span class="op">::</span><span class="kw">dbGetQuery</span>(</a>
<a class="sourceLine" id="cb154-3" data-line-number="3">  con,</a>
<a class="sourceLine" id="cb154-4" data-line-number="4">  <span class="st">&quot;</span></a>
<a class="sourceLine" id="cb154-5" data-line-number="5"><span class="st">  select &#39;single line comment, dtts&#39; showing       </span></a>
<a class="sourceLine" id="cb154-6" data-line-number="6"><span class="st">        ,*</span></a>
<a class="sourceLine" id="cb154-7" data-line-number="7"><span class="st">        ,current_database() db</span></a>
<a class="sourceLine" id="cb154-8" data-line-number="8"><span class="st">        ,user</span></a>
<a class="sourceLine" id="cb154-9" data-line-number="9"><span class="st">    --  ,to_char(now(),&#39;YYYY/MM/DD HH24:MI:SS&#39;) dtts</span></a>
<a class="sourceLine" id="cb154-10" data-line-number="10"><span class="st">    from store;    </span></a>
<a class="sourceLine" id="cb154-11" data-line-number="11"><span class="st">  &quot;</span>)</a>
<a class="sourceLine" id="cb154-12" data-line-number="12"><span class="kw">kable</span>(rs,<span class="dt">caption =</span> <span class="st">&#39;Sincle line comment&#39;</span>) </a></code></pre></div>
<table>
<caption><span id="tab:unnamed-chunk-10">Table 11.6: </span>Sincle line comment</caption>
<thead>
<tr class="header">
<th align="left">showing</th>
<th align="right">store_id</th>
<th align="right">manager_staff_id</th>
<th align="right">address_id</th>
<th align="left">last_update</th>
<th align="left">db</th>
<th align="left">user</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">single line comment, dtts</td>
<td align="right">1</td>
<td align="right">1</td>
<td align="right">1</td>
<td align="left">2006-02-15 09:57:12</td>
<td align="left">dvdrental</td>
<td align="left">postgres</td>
</tr>
<tr class="even">
<td align="left">single line comment, dtts</td>
<td align="right">2</td>
<td align="right">2</td>
<td align="right">2</td>
<td align="left">2006-02-15 09:57:12</td>
<td align="left">dvdrental</td>
<td align="left">postgres</td>
</tr>
</tbody>
</table>
<pre><code>The dtts  line is commented out with the two dashes and is dropped from the end of the result set columns.</code></pre>
</div>
<div id="multi-line-comment" class="section level4">
<h4><span class="header-section-number">11.3.2.2</span> 7. Multi-line comment /*…*/</h4>
<div class="sourceCode" id="cb156"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb156-1" data-line-number="1">rs &lt;-</a>
<a class="sourceLine" id="cb156-2" data-line-number="2"><span class="st">  </span>DBI<span class="op">::</span><span class="kw">dbGetQuery</span>(</a>
<a class="sourceLine" id="cb156-3" data-line-number="3">  con,</a>
<a class="sourceLine" id="cb156-4" data-line-number="4">  <span class="st">&quot;</span></a>
<a class="sourceLine" id="cb156-5" data-line-number="5"><span class="st">  select &#39;block comment drop db, user, and dtts&#39; showing</span></a>
<a class="sourceLine" id="cb156-6" data-line-number="6"><span class="st">        ,*</span></a>
<a class="sourceLine" id="cb156-7" data-line-number="7"><span class="st">        /*</span></a>
<a class="sourceLine" id="cb156-8" data-line-number="8"><span class="st">        ,current_database() db</span></a>
<a class="sourceLine" id="cb156-9" data-line-number="9"><span class="st">        ,user</span></a>
<a class="sourceLine" id="cb156-10" data-line-number="10"><span class="st">        ,to_char(now(),&#39;YYYY/MM/DD HH24:MI:SS&#39;) dtts</span></a>
<a class="sourceLine" id="cb156-11" data-line-number="11"><span class="st">        */</span></a>
<a class="sourceLine" id="cb156-12" data-line-number="12"><span class="st">    from store;    </span></a>
<a class="sourceLine" id="cb156-13" data-line-number="13"><span class="st">  &quot;</span>)</a>
<a class="sourceLine" id="cb156-14" data-line-number="14"><span class="kw">kable</span>(rs,<span class="dt">caption =</span> <span class="st">&#39;Multi-line comment&#39;</span>) </a></code></pre></div>
<table>
<caption><span id="tab:unnamed-chunk-11">Table 11.7: </span>Multi-line comment</caption>
<thead>
<tr class="header">
<th align="left">showing</th>
<th align="right">store_id</th>
<th align="right">manager_staff_id</th>
<th align="right">address_id</th>
<th align="left">last_update</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">block comment drop db, user, and dtts</td>
<td align="right">1</td>
<td align="right">1</td>
<td align="right">1</td>
<td align="left">2006-02-15 09:57:12</td>
</tr>
<tr class="even">
<td align="left">block comment drop db, user, and dtts</td>
<td align="right">2</td>
<td align="right">2</td>
<td align="right">2</td>
<td align="left">2006-02-15 09:57:12</td>
</tr>
</tbody>
</table>
<pre><code>The three columns db, user, and dtts, between the /\* and \*/ have been commented and no longer appear as the end columns of the result set.</code></pre>
</div>
</div>
<div id="from-clause" class="section level3">
<h3><span class="header-section-number">11.3.3</span> FROM Clause</h3>
<p>The <code>FROM</code> clause contains one or more datasets, usually database tables/views, from which the <code>SELECT</code> columns are derived. For now, in the examples, we are only using a single table. If the database reflects a relational model, your data is likely spread out over several tables. The key take away when beginning your analysis is to pick the table that has most of the data that you need for your analysis. This table becomes your main or driving table to build your SQL query statement around. After identifying your driving table, potentially save yourself a lot of time and heart ache, review any view that is built on your driving table. If one or more exist, especially, if vendor built, may already have the additional information needed for your analysis.</p>
<p>Insert SQL here or link to Views dependent on what</p>
<p>In this tutorial, there is only a single user hitting the database and row/table locking is not necessary and considered out of scope.</p>
<div id="table-uses" class="section level4">
<h4><span class="header-section-number">11.3.3.1</span> Table Uses</h4>
<ul>
<li>A table can be used more than once in a FROM clause. These are self-referencing tables. An example is an EMPLOYEE table which contains a foriegn key to her manager. Her manager also has a foriegn key to her manager, etc up the corporate ladder.<br />
</li>
<li><p>In the example above, the EMPLOYEE table plays two roles, employee and manager. The next line shows the FROM clause showing the same table used twice.</p>
<p>FROM EMPLOYEE EE, EMPLOYEE MGR</p></li>
<li>The EE and MGR are aliases for the EMPLOYEE table and represent the different roles the EMPLOYEE table plays.<br />
</li>
<li>Since all the column names are exactly the same for the EE and MGR role, the column names need to be prefixed with their role alias, e.g., SELECT MGR.EE_NAME, EE.EE_NAME … shows the manager name and her employee name(s) who work for her.</li>
<li>It is a good habit to always alias your tables and prefix your column names with the table alias to eliminate any ambiguity as to where the column came from. This is critical where there is inconsistent table column naming convention. It also helps when debugging larger SQL queries.</li>
<li><p>Cover inline tables in future section</p></li>
</ul>
<pre><code>Side Note: Do not create an unintended Cartesian join.  If one has more than one table in the FROM clause, make sure that every table in the FROM clause joins to at least one other table in the WHERE clause.  If your result set has an unexpectantly high rowcount and long runtime, check for a missing join in the FROM clause.</code></pre>
</div>
</div>
<div id="where-clause-row-selection-horizontal-partitioning-of-data" class="section level3">
<h3><span class="header-section-number">11.3.4</span> WHERE Clause: Row Selection – Horizontal Partitioning of Data</h3>
<p>In the previous SELECT clause section, the SELECT statement either partitioned data vertically across the table columns or derived vertical column values. This section provides examples that partitions the table data across rows in the table.</p>
<p>The WHERE clause defines all the conditions the data must meet to be included or excluded in the final result set. If all the conditions are met data is returned or it is rejected. This is commonly referred to as the data set filter condition.</p>
<pre><code>Side Note: For performance optimization reasons, the WHERE clause should reduce the dataset down to the smallest dataset as quickly as possible.  This is typically done using indexed columns, range conditions, and any other condition that rejects a lot of rows from being retrieved.</code></pre>
<p>The WHERE condition(s) can be simple or complex, but in the end are the appliction of the logic rules shown in the table below.</p>
<table>
<thead>
<tr class="header">
<th>p</th>
<th>q</th>
<th>p and q</th>
<th>p or q</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>T</td>
<td>T</td>
<td>T</td>
<td>T</td>
</tr>
<tr class="even">
<td>T</td>
<td>F</td>
<td>F</td>
<td>T</td>
</tr>
<tr class="odd">
<td>T</td>
<td>N</td>
<td>N</td>
<td>T</td>
</tr>
<tr class="even">
<td>F</td>
<td>F</td>
<td>F</td>
<td>F</td>
</tr>
<tr class="odd">
<td>F</td>
<td>N</td>
<td>F</td>
<td>T</td>
</tr>
<tr class="even">
<td>N</td>
<td>N</td>
<td>N</td>
<td>N</td>
</tr>
</tbody>
</table>
<p>When the filter logic is complex, it is sometimes easier to represent the where clause symbollically and apply a version of DeMorgan’s law which is shown below.</p>
<ol style="list-style-type: decimal">
<li>(A and B)’ = A’ or B’</li>
<li>(A or B)’ = A’ and B’</li>
</ol>
<div id="examples-continued" class="section level4">
<h4><span class="header-section-number">11.3.4.1</span> Examples Continued</h4>
<p>We begin with <code>1</code>, our simplest SQL query.</p>
<div class="sourceCode" id="cb160"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb160-1" data-line-number="1">rs &lt;-</a>
<a class="sourceLine" id="cb160-2" data-line-number="2"><span class="st">  </span>DBI<span class="op">::</span><span class="kw">dbGetQuery</span>(</a>
<a class="sourceLine" id="cb160-3" data-line-number="3">  con,</a>
<a class="sourceLine" id="cb160-4" data-line-number="4">  <span class="st">&quot;</span></a>
<a class="sourceLine" id="cb160-5" data-line-number="5"><span class="st">  select * from store;</span></a>
<a class="sourceLine" id="cb160-6" data-line-number="6"><span class="st">  &quot;</span>)</a>
<a class="sourceLine" id="cb160-7" data-line-number="7"><span class="kw">kable</span>(rs,<span class="dt">caption =</span> <span class="st">&#39;select all columns&#39;</span>)  </a></code></pre></div>
<table>
<caption><span id="tab:unnamed-chunk-12">Table 11.8: </span>select all columns</caption>
<thead>
<tr class="header">
<th align="right">store_id</th>
<th align="right">manager_staff_id</th>
<th align="right">address_id</th>
<th align="left">last_update</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">1</td>
<td align="right">1</td>
<td align="right">1</td>
<td align="left">2006-02-15 09:57:12</td>
</tr>
<tr class="even">
<td align="right">2</td>
<td align="right">2</td>
<td align="right">2</td>
<td align="left">2006-02-15 09:57:12</td>
</tr>
</tbody>
</table>
</div>
<div id="where-condition-logically-never-true." class="section level4">
<h4><span class="header-section-number">11.3.4.2</span> 8 WHERE condition logically never TRUE.</h4>
<div class="sourceCode" id="cb161"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb161-1" data-line-number="1">rs &lt;-</a>
<a class="sourceLine" id="cb161-2" data-line-number="2"><span class="st">  </span>DBI<span class="op">::</span><span class="kw">dbGetQuery</span>(</a>
<a class="sourceLine" id="cb161-3" data-line-number="3">  con,</a>
<a class="sourceLine" id="cb161-4" data-line-number="4">  <span class="st">&quot;</span></a>
<a class="sourceLine" id="cb161-5" data-line-number="5"><span class="st">  select * from store where 1 = 0;</span></a>
<a class="sourceLine" id="cb161-6" data-line-number="6"><span class="st">  &quot;</span>)</a>
<a class="sourceLine" id="cb161-7" data-line-number="7"><span class="kw">kable</span>(rs,<span class="dt">caption =</span> <span class="st">&#39;WHERE always FALSE&#39;</span>)  </a></code></pre></div>
<p>Table: (#tab:unnamed-chunk-13)WHERE always FALSE</p>
<p>store_id manager_staff_id address_id last_update
——— —————– ———– ————</p>
<pre><code>Since 1 = 0 is always false, no rows are ever returned.  Initially this construct seems useless, but actually is quite handy when debugging large scripts where a portion of the script needs to be turned off or when creating an empty table with the exact same column names and types as the FROM table(s).  </code></pre>
</div>
<div id="where-condition-logically-always-true." class="section level4">
<h4><span class="header-section-number">11.3.4.3</span> 9 WHERE condition logically always TRUE.</h4>
<div class="sourceCode" id="cb163"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb163-1" data-line-number="1">rs &lt;-</a>
<a class="sourceLine" id="cb163-2" data-line-number="2"><span class="st">  </span>DBI<span class="op">::</span><span class="kw">dbGetQuery</span>(</a>
<a class="sourceLine" id="cb163-3" data-line-number="3">  con,</a>
<a class="sourceLine" id="cb163-4" data-line-number="4">  <span class="st">&quot;</span></a>
<a class="sourceLine" id="cb163-5" data-line-number="5"><span class="st">  select * from store where 1 = 1;</span></a>
<a class="sourceLine" id="cb163-6" data-line-number="6"><span class="st">  &quot;</span>)</a>
<a class="sourceLine" id="cb163-7" data-line-number="7"><span class="kw">kable</span>(rs,<span class="dt">caption =</span> <span class="st">&#39;WHERE always TRUE&#39;</span>)  </a></code></pre></div>
<table>
<caption><span id="tab:unnamed-chunk-14">Table 11.10: </span>WHERE always TRUE</caption>
<thead>
<tr class="header">
<th align="right">store_id</th>
<th align="right">manager_staff_id</th>
<th align="right">address_id</th>
<th align="left">last_update</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">1</td>
<td align="right">1</td>
<td align="right">1</td>
<td align="left">2006-02-15 09:57:12</td>
</tr>
<tr class="even">
<td align="right">2</td>
<td align="right">2</td>
<td align="right">2</td>
<td align="left">2006-02-15 09:57:12</td>
</tr>
</tbody>
</table>
<pre><code>Since 1 = 1 is always true, all rows are always returned.  Initially this construct seems useless, but actually is also quite handy when debugging large scripts and creating a backup of table.</code></pre>
</div>
<div id="where-equality-condition" class="section level4">
<h4><span class="header-section-number">11.3.4.4</span> 10 WHERE equality condition</h4>
<div class="sourceCode" id="cb165"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb165-1" data-line-number="1">rs &lt;-</a>
<a class="sourceLine" id="cb165-2" data-line-number="2"><span class="st">  </span>DBI<span class="op">::</span><span class="kw">dbGetQuery</span>(</a>
<a class="sourceLine" id="cb165-3" data-line-number="3">  con,</a>
<a class="sourceLine" id="cb165-4" data-line-number="4">  <span class="st">&quot;</span></a>
<a class="sourceLine" id="cb165-5" data-line-number="5"><span class="st">  select * from store where store_id = 2;</span></a>
<a class="sourceLine" id="cb165-6" data-line-number="6"><span class="st">  &quot;</span>)</a>
<a class="sourceLine" id="cb165-7" data-line-number="7"><span class="kw">kable</span>(rs,<span class="dt">caption =</span> <span class="st">&#39;WHERE EQUAL&#39;</span>)  </a></code></pre></div>
<table>
<caption><span id="tab:unnamed-chunk-15">Table 11.11: </span>WHERE EQUAL</caption>
<thead>
<tr class="header">
<th align="right">store_id</th>
<th align="right">manager_staff_id</th>
<th align="right">address_id</th>
<th align="left">last_update</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">2</td>
<td align="right">2</td>
<td align="right">2</td>
<td align="left">2006-02-15 09:57:12</td>
</tr>
</tbody>
</table>
<pre><code>    The only row where the store_id = 2 is row 2 and it is the only row returned.
    </code></pre>
</div>
<div id="where-not-equal-conditions" class="section level4">
<h4><span class="header-section-number">11.3.4.5</span> 11 WHERE NOT equal conditions</h4>
<div class="sourceCode" id="cb167"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb167-1" data-line-number="1">rs &lt;-</a>
<a class="sourceLine" id="cb167-2" data-line-number="2"><span class="st">  </span>DBI<span class="op">::</span><span class="kw">dbGetQuery</span>(</a>
<a class="sourceLine" id="cb167-3" data-line-number="3">  con,</a>
<a class="sourceLine" id="cb167-4" data-line-number="4">  <span class="st">&quot;</span></a>
<a class="sourceLine" id="cb167-5" data-line-number="5"><span class="st">  select * from store where store_id &lt;&gt; 2;</span></a>
<a class="sourceLine" id="cb167-6" data-line-number="6"><span class="st">  &quot;</span>)</a>
<a class="sourceLine" id="cb167-7" data-line-number="7"><span class="kw">kable</span>(rs,<span class="dt">caption =</span> <span class="st">&#39;WHERE NOT EQUAL&#39;</span>)  </a></code></pre></div>
<table>
<caption><span id="tab:unnamed-chunk-16">Table 11.12: </span>WHERE NOT EQUAL</caption>
<thead>
<tr class="header">
<th align="right">store_id</th>
<th align="right">manager_staff_id</th>
<th align="right">address_id</th>
<th align="left">last_update</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">1</td>
<td align="right">1</td>
<td align="right">1</td>
<td align="left">2006-02-15 09:57:12</td>
</tr>
</tbody>
</table>
<pre><code>&lt;&gt; is syntactically the same as !=
    
    The only row where the store_id &lt;&gt; 2 is row 1 and only row 1 is returned.  </code></pre>
</div>
<div id="where-or-condition" class="section level4">
<h4><span class="header-section-number">11.3.4.6</span> 12 WHERE OR condition</h4>
<div class="sourceCode" id="cb169"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb169-1" data-line-number="1">rs &lt;-</a>
<a class="sourceLine" id="cb169-2" data-line-number="2"><span class="st">  </span>DBI<span class="op">::</span><span class="kw">dbGetQuery</span>(</a>
<a class="sourceLine" id="cb169-3" data-line-number="3">  con,</a>
<a class="sourceLine" id="cb169-4" data-line-number="4">  <span class="st">&quot;</span></a>
<a class="sourceLine" id="cb169-5" data-line-number="5"><span class="st">  select * from store where manager_staff_id = 1 or store_id &lt; 3; </span></a>
<a class="sourceLine" id="cb169-6" data-line-number="6"><span class="st">  &quot;</span>)</a>
<a class="sourceLine" id="cb169-7" data-line-number="7"><span class="kw">kable</span>(rs,<span class="dt">caption =</span> <span class="st">&#39;WHERE OR condition&#39;</span>)  </a></code></pre></div>
<table>
<caption><span id="tab:unnamed-chunk-17">Table 11.13: </span>WHERE OR condition</caption>
<thead>
<tr class="header">
<th align="right">store_id</th>
<th align="right">manager_staff_id</th>
<th align="right">address_id</th>
<th align="left">last_update</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">1</td>
<td align="right">1</td>
<td align="right">1</td>
<td align="left">2006-02-15 09:57:12</td>
</tr>
<tr class="even">
<td align="right">2</td>
<td align="right">2</td>
<td align="right">2</td>
<td align="left">2006-02-15 09:57:12</td>
</tr>
</tbody>
</table>
<pre><code>The first condition manager_staff_id = 1 returns a single row and the second condition store_id &lt; 3 returns two rows.  </code></pre>
<p>Following table is modified from <a href="http://www.tutorialspoint.com/sql/sql-operators" class="uri">http://www.tutorialspoint.com/sql/sql-operators</a></p>
<p>SQL Comparison Operators</p>
<table>
<colgroup>
<col width="10%" />
<col width="75%" />
<col width="14%" />
</colgroup>
<thead>
<tr class="header">
<th>Operator</th>
<th>Description</th>
<th>example</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>=</td>
<td>Checks if the values of two operands are equal or not, if yes then condition becomes true.</td>
<td>(a = b) is not true.</td>
</tr>
<tr class="even">
<td>!=</td>
<td>Checks if the values of two operands are equal or not, if values are not equal then condition becomes true.</td>
<td>(a != b) is true.</td>
</tr>
<tr class="odd">
<td>&lt;&gt;</td>
<td>Checks if the values of two operands are equal or not, if values are not equal then condition becomes true.</td>
<td>(a &lt;&gt; b) is true.</td>
</tr>
<tr class="even">
<td>&gt;</td>
<td>Checks if the value of left operand is greater than the value of right operand, if yes then condition becomes true.</td>
<td>(a &gt; b) is not true.</td>
</tr>
<tr class="odd">
<td>&lt;</td>
<td>Checks if the value of left operand is less than the value of right operand, if yes then condition becomes true.</td>
<td>(a &lt; b) is true.</td>
</tr>
<tr class="even">
<td>&gt;=</td>
<td>Checks if the value of left operand is greater than or equal to the value of right operand, if yes then condition becomes true.</td>
<td>(a &gt;= b) is not true.</td>
</tr>
<tr class="odd">
<td>&lt;=</td>
<td>Checks if the value of left operand is less than or equal to the value of right operand, if yes then condition becomes true.</td>
<td>(a &lt;= b) is true.</td>
</tr>
<tr class="even">
<td>!&lt;</td>
<td>Checks if the value of left operand is not less than the value of right operand, if yes then condition becomes true.</td>
<td>(a !&lt; b) is false.</td>
</tr>
<tr class="odd">
<td>!&gt;</td>
<td>Checks if the value of left operand is not greater than the value of right operand, if yes then condition becomes true.</td>
<td>(a !&gt; b) is true.</td>
</tr>
</tbody>
</table>
<table>
<colgroup>
<col width="8%" />
<col width="91%" />
</colgroup>
<thead>
<tr class="header">
<th>Operator</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>ALL</td>
<td>The ALL operator is used to compare a value to all values in another value set.</td>
</tr>
<tr class="even">
<td>AND</td>
<td>The AND operator allows the existence of multiple conditions in an SQL statement’s WHERE clause.</td>
</tr>
<tr class="odd">
<td>ANY</td>
<td>The ANY operator is used to compare a value to any applicable value in the list as per the condition.</td>
</tr>
<tr class="even">
<td>BETWEEN</td>
<td>The BETWEEN operator is used to search for values that are within a set of values, given the minimum value and the maximum value.</td>
</tr>
<tr class="odd">
<td>EXISTS</td>
<td>The EXISTS operator is used to search for the presence of a row in a specified table that meets a certain criterion.</td>
</tr>
<tr class="even">
<td>IN</td>
<td>The IN operator is used to compare a value to a list of literal values that have been specified.</td>
</tr>
<tr class="odd">
<td>LIKE</td>
<td>The LIKE operator is used to compare a value to similar values using wildcard operators.</td>
</tr>
<tr class="even">
<td>NOT</td>
<td>The NOT operator reverses the meaning of the logical operator with which it is used. Eg: NOT EXISTS, NOT BETWEEN, NOT IN, etc. This is a negate operator.</td>
</tr>
<tr class="odd">
<td>OR</td>
<td>The OR operator is used to combine multiple conditions in an SQL statement’s WHERE clause.</td>
</tr>
<tr class="even">
<td>IS NULL</td>
<td>The NULL operator is used to compare a value with a NULL value.</td>
</tr>
<tr class="odd">
<td>UNIQUE</td>
<td>The UNIQUE operator searches every row of a specified table for uniqueness (no duplicates).</td>
</tr>
</tbody>
</table>
<p><a href="https://pgexercises.com/questions/basic" class="uri">https://pgexercises.com/questions/basic</a></p>
<p>## TO-DO’s</p>
<ol style="list-style-type: decimal">
<li>inline tables</li>
<li>correlated subqueries</li>
</ol>
</div>
</div>
</div>
<div id="paradigm-shift-from-r-dplyr-to-sql" class="section level2">
<h2><span class="header-section-number">11.4</span> Paradigm Shift from R-Dplyr to SQL</h2>
<p>Paraphrasing what some have said with an R dplyr background and no SQL experience, “It is like working from the inside out.” This sentiment occurs because</p>
<ol style="list-style-type: decimal">
<li>The SQL SELECT statement begins at the end, the SELECT clause, and drills backwards, loosely speaking, to derive the desired result set.</li>
<li>SQL SELECT statements are an all or nothing proposition. One gets nothing if there is any kind of syntax error.<br />
</li>
<li>SQL SELECT result sets can be quite opaque. The WHERE clause can be very dense and difficult to trace through. It is rarely ever linear in nature.<br />
</li>
<li>Validating all the permutations in the where clause can be tough and tedious.</li>
</ol>
<div id="big-bang-versus-piped-incremental-steps." class="section level3">
<h3><span class="header-section-number">11.4.1</span> Big bang versus piped incremental steps.</h3>
<ol style="list-style-type: decimal">
<li>Dplyr starts with one or more sources joined together in a conceptually similar way that SQL joins sources.</li>
<li>The pipe and filter() function breaks down the filter conditions into small managable logical steps. This makes it much easier to understand what is happening in the derivation of the final tibble. Adding tees through out the pipe line gives one full trace back of all the data transformations at every pipe.</li>
</ol>
<p>Helpful tidyverse functions that output tibbles: tbl_module function in <a href="https://github.com/nhemerson/tibbleColumns" class="uri">https://github.com/nhemerson/tibbleColumns</a> package;</p>
<p>Mental picture: SQL approach: Imagine a data lake named Niagera Falls and drinking from it without drowning. R-Dplyr approach: Imagine a resturant at the bottom of the Niagera Falls data lake and having a refreshing dring out of the water faucet.</p>
</div>
<div id="sql-execution-order" class="section level3">
<h3><span class="header-section-number">11.4.2</span> SQL Execution Order</h3>
<p>The table below is derived from this site. <a href="https://www.periscopedata.com/blog/sql-query-order-of-operations" class="uri">https://www.periscopedata.com/blog/sql-query-order-of-operations</a> It shows what goes on under the hood SQL SELECT hood.</p>
<table>
<colgroup>
<col width="3%" />
<col width="19%" />
<col width="47%" />
<col width="29%" />
</colgroup>
<thead>
<tr class="header">
<th>SEQ</th>
<th>SQL</th>
<th>Function</th>
<th>Dplyr</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>WITH</td>
<td>Common Table expression, CTE, one or more datasets/tables used FROM clause.</td>
<td>.data parameter in dplyr functions</td>
</tr>
<tr class="even">
<td>2</td>
<td>FROM</td>
<td>Choose and join tables to get base data</td>
<td>.data parameter in dplyr functions</td>
</tr>
<tr class="odd">
<td>3</td>
<td>ON</td>
<td>Choose and join tables to get base data</td>
<td>dplyr join family of functions</td>
</tr>
<tr class="even">
<td>4</td>
<td>JOIN</td>
<td>Choose and join tables to get base data</td>
<td>dplyr join family of functions</td>
</tr>
<tr class="odd">
<td>5</td>
<td>WHERE</td>
<td>filters the base data</td>
<td>dplyr filter()</td>
</tr>
<tr class="even">
<td>6</td>
<td>GROUP BY</td>
<td>aggregates the base data</td>
<td>dplyr group_by family of functions</td>
</tr>
<tr class="odd">
<td>7</td>
<td>WITH CUBE/ROLLUP</td>
<td>aggregates the base data</td>
<td>is this part of the dplyr grammar</td>
</tr>
<tr class="even">
<td>8</td>
<td>HAVING</td>
<td>filters aggregated data</td>
<td>dplyr filter()</td>
</tr>
<tr class="odd">
<td>9</td>
<td>SELECT</td>
<td>Returns final data set</td>
<td>dplyr select()</td>
</tr>
<tr class="even">
<td>10</td>
<td>DISTINCT</td>
<td>Dedupe the final data set</td>
<td>dplyr distinct()</td>
</tr>
<tr class="odd">
<td>11</td>
<td>ORDER BY</td>
<td>Sorts the final data set</td>
<td>arrange()</td>
</tr>
<tr class="even">
<td>12</td>
<td>TOP/LIMIT</td>
<td>Limits the number of rows in data set</td>
</tr>
<tr class="odd">
<td>13</td>
<td>OFFSET/FETCH</td>
<td>Limits the number of rows in data set</td>
</tr>
</tbody>
</table>
<p>The SEQ column shows the standard order of SQL execution. One take away for this tutorial is that the SELECT clause actually executes late in the process, even though it is the first clause in the entire SELECT statement. A second take away is that SQL execution order, or tweaked order, plays a critical role in SQL query tuning.</p>
<ol start="6" style="list-style-type: decimal">
<li>SQL for View table dependencies.</li>
<li>Add cartesian join exercise.</li>
</ol>

<div class="sourceCode" id="cb171"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb171-1" data-line-number="1">dplyr_summary_df &lt;-</a>
<a class="sourceLine" id="cb171-2" data-line-number="2"><span class="st">    </span><span class="kw">read.delim</span>( <span class="kw">here</span>(</a>
<a class="sourceLine" id="cb171-3" data-line-number="3">    <span class="st">&#39;11_dplyr_sql_summary_table.rmd&#39;</span>),</a>
<a class="sourceLine" id="cb171-4" data-line-number="4">    <span class="dt">header =</span> <span class="ot">TRUE</span>,</a>
<a class="sourceLine" id="cb171-5" data-line-number="5">    <span class="dt">sep =</span> <span class="st">&#39;|&#39;</span>,</a>
<a class="sourceLine" id="cb171-6" data-line-number="6">    <span class="dt">as.is =</span> <span class="ot">TRUE</span></a>
<a class="sourceLine" id="cb171-7" data-line-number="7">    )</a>
<a class="sourceLine" id="cb171-8" data-line-number="8"></a>
<a class="sourceLine" id="cb171-9" data-line-number="9"><span class="kw">display_rs</span>(MODE,dplyr_summary_df,display_rows)</a></code></pre></div>
<p>In Dplyr.Function description SQL.Clause Notes Category<br />
— ——————————————————————————————————————————————————————————- —————————————————————– ——————————————————————- ————————– ——————————————-
– ————————————– ——————————————- ——————————– ————————- ————-<br />
Y arrange() Arrange rows by variables ORDER BY Basic single-table verbs<br />
Y? distinct() Return rows with matching conditions SELECT distinct * Basic single-table verbs<br />
Y select() rename() Select/rename variables by name SELECT column_name alias_name Basic single-table verbs<br />
N pull() Pull out a single variable SELECT column_name; Basic single-table verbs<br />
Y mutate() transmute() Add new variables SELECT computed_value computed_name Basic single-table verbs<br />
Y summarise() summarize() Reduces multiple values down to a single value SELECT aggregate_functions GROUP BY Basic single-table verbs<br />
N group_by() ungroup() Objects exported from other packages GROUP BY no ungroup Basic single-table verbs<br />
N distinct() Select distinct/unique rows SELECT distinct {colname1,…colnamen} Basic single-table verbs<br />
N do() Do anything NA Basic single-table verbs<br />
N sample_n() sample_frac() Sample n rows from a table ORDER BY RANDOM() LIMIT 10 Basic single-table verbs<br />
N slice() Select rows by position SELECT row_number() over (partition by expression(s) order_by exp) Basic single-table verbs<br />
Y tally() count() add_tally() add_count() Count/tally observations by group GROUP BY Single-table helpers<br />
Y top_n() Select top (or bottom) n rows (by value) ORDER BY VALUE {DESC} LIMIT 10 Single-table helpers<br />
N arrange_all() arrange_at() arrange_if() Arrange rows by a selection of variables ORDER BY scoped-Operate on a selection of variables
N filter_all() filter_if() filter_at() Filter within a selection of variables scoped-Operate on a selection of variables
N group_by_all() group_by_at() group_by_if() Group by a selection of variables scoped-Operate on a selection of variables
N select_all() rename_all() select_if() rename_if() select_at() rename_at() Select and rename a selection of variables scoped-Operate on a selection of variables
N summarise_all() summarise_if() summarise_at() summarize_all() summarize_if() summarize_at() mutate_all() mutate_if() mutate_at() transmute_all() transmute_if() transmute_at() Summarise and mutate multiple columns. scoped-Operate on a selection of variables
N all_vars() any_vars() Apply predicate to all variables scoped-Operate on a selection of variables
N vars() Select variables scoped-Operate on a selection of variables
N funs() Create a list of functions calls. scoped-Operate on a selection of variables
N all_equal() all.equal(<tbl_df>) Flexible equality comparison for data frames Two-table verbs<br />
N bind_rows() bind_cols() combine() Efficiently bind multiple data frames by row and column Two-table verbs<br />
N intersect() union() union_all() setdiff() setequal() Set operations Two-table verbs<br />
N inner_join() left_join() right_join() full_join() semi_join() anti_join() Join two tbls together Two-table verbs<br />
N inner_join(<tbl_df>) left_join(<tbl_df>) right_join(<tbl_df>) full_join(<tbl_df>) semi_join(<tbl_df>) anti_join(<tbl_df>) Join data frame tbls Two-table verbs<br />
N auto_copy() Copy tables to same source, if necessary Remote tables<br />
N compute() collect() collapse() Force computation of a database query Remote tables<br />
N copy_to() Copy a local data frame to a remote src Remote tables<br />
N ident() Flag a character vector as SQL identifiers Remote tables<br />
N explain() show_query() Explain details of a tbl Remote tables<br />
N tbl() is.tbl() as.tbl() Create a table from a data source Remote tables<br />
N src_mysql() src_postgres() src_sqlite() Source for database backends Remote tables<br />
N sql() SQL escaping. Remote tables<br />
N groups() group_vars() Return grouping variables Metadata<br />
N between() Do values in a numeric vector fall in specified range? Vector functions<br />
N case_when() A general vectorised if Vector functions<br />
N coalesce() Find first non-missing element Vector functions<br />
N cumall() cumany() cummean() Cumulativate versions of any, all, and mean Vector functions<br />
N desc() Descending order Vector functions<br />
N if_else() Vectorised if Vector functions<br />
N lead() lag() Lead and lag. Vector functions<br />
N order_by() A helper function for ordering window function output Vector functions<br />
N n() The number of observations in the current group. Vector functions<br />
N n_distinct() Efficiently count the number of unique values in a set of vector Vector functions<br />
N na_if() Convert values to NA Vector functions<br />
N near() Compare two numeric vectors Vector functions<br />
N nth() first() last() Extract the first, last or nth value from a vector Vector functions<br />
N row_number() ntile() min_rank() dense_rank() percent_rank() cume_dist() Windowed rank functions. Vector functions<br />
N recode() recode_factor() Recode values Vector functions<br />
N band_members band_instruments band_instruments2 Band membership Data<br />
N nasa NASA spatio-temporal data Data<br />
N starwars Starwars characters Data<br />
N storms Storm tracks data Data<br />
N tbl_cube() A data cube tbl Other backends<br />
N as.table(<tbl_cube>) as.data.frame(<tbl_cube>) as_data_frame(<tbl_cube>) Coerce a tbl_cube to other data structures Other backends<br />
N as.tbl_cube() Coerce an existing data structure into a tbl_cube Other backends<br />
N rowwise() Group input by rows Other backends</p>
<p>Start up the <code>docker-pet</code> container</p>
<div class="sourceCode" id="cb172"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb172-1" data-line-number="1"><span class="kw">sp_docker_start</span>(<span class="st">&quot;sql-pet&quot;</span>)</a></code></pre></div>
<p>Now connect to the <code>dvdrental</code> database with R</p>
<pre><code>## &lt;PqConnection&gt; dvdrental@localhost:5432</code></pre>
</div>
<div id="which-server" class="section level3">
<h3><span class="header-section-number">11.4.3</span> Which Server?</h3>
<p>Your data may actually be spread across multiple servers, DEV, QA, and PROD servers.</p>
<p>For this tutorial, your laptop is a server for the Docker Postgres databases. A database is a collection of files that Postgres manages in the background.</p>
<div id="htmlwidget-1d9f9b9fdca3023baa83" style="width:672px;height:480px;" class="grViz html-widget"></div>
<script type="application/json" data-for="htmlwidget-1d9f9b9fdca3023baa83">{"x":{"diagram":"\ndigraph DB_Environment {\n    graph [overlap = true, fontsize = 10, rankdir=LR, height= 10]\n\n    node [shape = box,fontname = Helvetica,fontcolor=blue]\n         Servers;\n\n    node [shape = box,fontname = Helvetica,fontcolor=\"\"]\n        DBs; Schemas; Tables;\n\n    edge [arrowhead = crow, arrowtail = tee]       \n    Servers -> DBs -> Schemas -> Tables\n}\n","config":{"engine":"dot","options":null}},"evals":[],"jsHooks":[]}</script>
</div>
<div id="which-database" class="section level3">
<h3><span class="header-section-number">11.4.4</span> Which database?</h3>
<p>Your DBA will create your user accounts and priviledges for the database(s) that you can access.</p>
<p>One of the challenges when working with a database(s) is finding where your data actually resides. Your best resources will be one or more vendor consultants, business subject matter experts, <code>SME</code>, and your DBA(s). Don’t be surprised if the vendor consultants and SME’s don’t always agree what the data actually means. The data form, fit, and function could have changed overtime due to an application upgrade or a government regulatory mandate.</p>
<p>Your data may actually reside in multiple databases, e.g., a detail and summary databases. It is not unusual to have 100’s of databases in a corporate environment. Today some of your databases may physically reside on site or newer ones may reside in the cloud.</p>
<div id="htmlwidget-b18b48ec4ad649442f3b" style="width:672px;height:480px;" class="DiagrammeR html-widget"></div>
<script type="application/json" data-for="htmlwidget-b18b48ec4ad649442f3b">{"x":{"diagram":"\ngraph LR\n  A{DB}-->DB1\n  A-->DBx\n  A-->DBn\n\n\n  DB1-->Schema1_1\n  DB1-->Schema1_x[Schema1_x]\n  DB1-->Schema1_n\n\n  DBx-->Schema{Schema}\n  Schema-->Schema_x_1\n  Schema-->Schema_x_x\n  Schema_x_x-->Table_x_1\n  Schema_x_x-->Table_x_x\n  Schema_x_x-->Table_x_n\n  Schema-->Schema_x_n\n  \n\n  DBn-->Schema_n_1\n  DBn-->Schema_n_x\n  DBn-->Schema_n_n\n"},"evals":[],"jsHooks":[]}</script>
<p>In our tutorial, we focus on the one database, <code>dvdrental</code>. Database names usually reflect something about the data that they contain.</p>
</div>
<div id="how-do-i-check-for-databases" class="section level3">
<h3><span class="header-section-number">11.4.5</span> How do I check for databases?</h3>
<p>Each vendor tracks database information in their own tables. We can find the Postgres databases in the pg_database; Two Oracle objects that contain DB information are V<span class="math inline">\(DATABASE and V\)</span>INSTANCE.</p>
<div class="sourceCode" id="cb174"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb174-1" data-line-number="1">rs &lt;-</a>
<a class="sourceLine" id="cb174-2" data-line-number="2"><span class="st">  </span>DBI<span class="op">::</span><span class="kw">dbGetQuery</span>(</a>
<a class="sourceLine" id="cb174-3" data-line-number="3">  con,</a>
<a class="sourceLine" id="cb174-4" data-line-number="4">  <span class="st">&quot;SELECT &#39;DB Names in Docker&#39; showing</span></a>
<a class="sourceLine" id="cb174-5" data-line-number="5"><span class="st">          ,datname DB,*</span></a>
<a class="sourceLine" id="cb174-6" data-line-number="6"><span class="st">     FROM pg_catalog.pg_database</span></a>
<a class="sourceLine" id="cb174-7" data-line-number="7"><span class="st">    WHERE datistemplate = false;</span></a>
<a class="sourceLine" id="cb174-8" data-line-number="8"><span class="st">  &quot;</span></a>
<a class="sourceLine" id="cb174-9" data-line-number="9">  )</a>
<a class="sourceLine" id="cb174-10" data-line-number="10"><span class="kw">kable</span>(rs)</a></code></pre></div>
<table>
<thead>
<tr class="header">
<th align="left">showing</th>
<th align="left">db</th>
<th align="left">datname</th>
<th align="right">datdba</th>
<th align="right">encoding</th>
<th align="left">datcollate</th>
<th align="left">datctype</th>
<th align="left">datistemplate</th>
<th align="left">datallowconn</th>
<th align="right">datconnlimit</th>
<th align="right">datlastsysoid</th>
<th align="left">datfrozenxid</th>
<th align="left">datminmxid</th>
<th align="right">dattablespace</th>
<th align="left">datacl</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">DB Names in Docker</td>
<td align="left">postgres</td>
<td align="left">postgres</td>
<td align="right">10</td>
<td align="right">6</td>
<td align="left">en_US.utf8</td>
<td align="left">en_US.utf8</td>
<td align="left">FALSE</td>
<td align="left">TRUE</td>
<td align="right">-1</td>
<td align="right">12993</td>
<td align="left">548</td>
<td align="left">1</td>
<td align="right">1663</td>
<td align="left">NA</td>
</tr>
<tr class="even">
<td align="left">DB Names in Docker</td>
<td align="left">dvdrental</td>
<td align="left">dvdrental</td>
<td align="right">10</td>
<td align="right">6</td>
<td align="left">en_US.utf8</td>
<td align="left">en_US.utf8</td>
<td align="left">FALSE</td>
<td align="left">TRUE</td>
<td align="right">-1</td>
<td align="right">12993</td>
<td align="left">548</td>
<td align="left">1</td>
<td align="right">1663</td>
<td align="left">NA</td>
</tr>
</tbody>
</table>
</div>
<div id="how-do-i-change-my-database-connections" class="section level3">
<h3><span class="header-section-number">11.4.6</span> How do I change my database connections</h3>
<pre><code>Exercise: In the next codeblock, modify the connection call to connect to the `postgres` database.

The code block will then disconnect you from the postgres database and reconnect you to the dvdrental database.</code></pre>
<div class="sourceCode" id="cb176"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb176-1" data-line-number="1"><span class="co"># connect to postgres DB</span></a>
<a class="sourceLine" id="cb176-2" data-line-number="2">con &lt;-<span class="st"> </span><span class="kw">sp_get_postgres_connection</span>(</a>
<a class="sourceLine" id="cb176-3" data-line-number="3">  <span class="dt">user =</span> <span class="kw">Sys.getenv</span>(<span class="st">&quot;DEFAULT_POSTGRES_USER_NAME&quot;</span>),</a>
<a class="sourceLine" id="cb176-4" data-line-number="4">  <span class="dt">password =</span>  <span class="kw">Sys.getenv</span>(<span class="st">&quot;DEFAULT_POSTGRES_PASSWORD&quot;</span>),</a>
<a class="sourceLine" id="cb176-5" data-line-number="5">  <span class="dt">dbname =</span> <span class="st">&quot;eneter db name here&quot;</span>,</a>
<a class="sourceLine" id="cb176-6" data-line-number="6">  <span class="dt">seconds_to_test =</span> <span class="dv">10</span>)</a>
<a class="sourceLine" id="cb176-7" data-line-number="7"></a>
<a class="sourceLine" id="cb176-8" data-line-number="8">con</a></code></pre></div>
<pre><code>## [1] &quot;There is no connection&quot;</code></pre>
<div class="sourceCode" id="cb178"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb178-1" data-line-number="1"><span class="co"># Disconnect if successful</span></a>
<a class="sourceLine" id="cb178-2" data-line-number="2"><span class="cf">if</span> (<span class="kw">class</span>(con) <span class="op">==</span><span class="st"> &#39;PqConnection&#39;</span>)</a>
<a class="sourceLine" id="cb178-3" data-line-number="3">    <span class="kw">dbDisconnect</span>(con)</a>
<a class="sourceLine" id="cb178-4" data-line-number="4"></a>
<a class="sourceLine" id="cb178-5" data-line-number="5"><span class="co">#Answer: con &lt;PqConnection&gt; postgres@localhost:5432</span></a>
<a class="sourceLine" id="cb178-6" data-line-number="6"></a>
<a class="sourceLine" id="cb178-7" data-line-number="7"><span class="co"># Reconnect to dvdrental</span></a>
<a class="sourceLine" id="cb178-8" data-line-number="8"></a>
<a class="sourceLine" id="cb178-9" data-line-number="9">con &lt;-<span class="st"> </span><span class="kw">sp_get_postgres_connection</span>(</a>
<a class="sourceLine" id="cb178-10" data-line-number="10">  <span class="dt">user =</span> <span class="kw">Sys.getenv</span>(<span class="st">&quot;DEFAULT_POSTGRES_USER_NAME&quot;</span>),</a>
<a class="sourceLine" id="cb178-11" data-line-number="11">  <span class="dt">password =</span>  <span class="kw">Sys.getenv</span>(<span class="st">&quot;DEFAULT_POSTGRES_PASSWORD&quot;</span>),</a>
<a class="sourceLine" id="cb178-12" data-line-number="12">  <span class="dt">dbname =</span> <span class="st">&quot;dvdrental&quot;</span>,</a>
<a class="sourceLine" id="cb178-13" data-line-number="13">  <span class="dt">seconds_to_test =</span> <span class="dv">10</span>)</a>
<a class="sourceLine" id="cb178-14" data-line-number="14">con</a></code></pre></div>
<pre><code>## &lt;PqConnection&gt; dvdrental@localhost:5432</code></pre>
<p>Note that the two Sys.getenv function calls work in this tutorial because both the user and password are available in both databases. This is a common practice in organizations that have implemented single sign on across their organization.</p>
</div>
<div id="sql_be_stinger_01" class="section level3">
<h3><span class="header-section-number">11.4.7</span> SQL_BE_STINGER_01:</h3>
<pre><code>   If one has data in multiple databases or multiple environments, Development, Integration, and Prodution, it is very easy to connect to the wrong database in the wrong environment especially when testing changes.  
   
   Always double check your connection information when logging in and before performing any inserts, updates, or deletes against the database.</code></pre>
<p>The following code block, customize to your liking, should be used to reduce propagating the above STINGER. Current_database(), CURRENT_DATE or CURRENT_TIMESTAMP, and showing are the most useful and last three not so much. Instead of the host IP address which is great if you are a computer, having the actual host name mnemonic name would be a nice. Most organization naming conventions will indicate something useful about the host.</p>
<div id="dplyr-feature-implemented-in-sql" class="section level4">
<h4><span class="header-section-number">11.4.7.1</span> dplyr feature implemented in SQL</h4>
<table>
<thead>
<tr class="header">
<th align="left">In</th>
<th align="left">Dplyr.Function</th>
<th align="left">description</th>
<th align="left">SQL.Clause</th>
<th align="left">Notes</th>
<th align="left">Category</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Y</td>
<td align="left">mutate() transmute()</td>
<td align="left">Add new variables</td>
<td align="left">SELECT computed_value computed_name</td>
<td align="left"></td>
<td align="left">Basic single-table verbs</td>
</tr>
<tr class="even">
<td align="left">## SQ</td>
<td align="left">L_BE_01 How do implemen</td>
<td align="left">t standardized SQL M</td>
<td align="left">etaData Information?</td>
<td align="left"></td>
<td align="left"></td>
</tr>
</tbody>
</table>
<div class="sourceCode" id="cb181"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb181-1" data-line-number="1"><span class="co">#SQL_BE_01|Standard SQL MetaData Columns</span></a>
<a class="sourceLine" id="cb181-2" data-line-number="2">SQL_BE_<span class="dv">01</span> &lt;-</a>
<a class="sourceLine" id="cb181-3" data-line-number="3"><span class="st">  </span>DBI<span class="op">::</span><span class="kw">dbGetQuery</span>(</a>
<a class="sourceLine" id="cb181-4" data-line-number="4">  con,</a>
<a class="sourceLine" id="cb181-5" data-line-number="5">  <span class="st">&quot;SELECT current_database() DB</span></a>
<a class="sourceLine" id="cb181-6" data-line-number="6"><span class="st">         ,CURRENT_DATE</span></a>
<a class="sourceLine" id="cb181-7" data-line-number="7"><span class="st">         ,CURRENT_TIMESTAMP</span></a>
<a class="sourceLine" id="cb181-8" data-line-number="8"><span class="st">         ,&#39;result set description&#39; showing</span></a>
<a class="sourceLine" id="cb181-9" data-line-number="9"><span class="st">         ,session_user</span></a>
<a class="sourceLine" id="cb181-10" data-line-number="10"><span class="st">         ,inet_server_addr() host</span></a>
<a class="sourceLine" id="cb181-11" data-line-number="11"><span class="st">         ,inet_server_port() port</span></a>
<a class="sourceLine" id="cb181-12" data-line-number="12"><span class="st">  &quot;</span></a>
<a class="sourceLine" id="cb181-13" data-line-number="13">  )</a>
<a class="sourceLine" id="cb181-14" data-line-number="14"><span class="kw">kable</span>(<span class="kw">head</span>(SQL_BE_<span class="dv">01</span>,display_rows))</a></code></pre></div>
<table>
<thead>
<tr class="header">
<th align="left">db</th>
<th align="left">current_date</th>
<th align="left">current_timestamp</th>
<th align="left">showing</th>
<th align="left">session_user</th>
<th align="left">host</th>
<th align="right">port</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">dvdrental</td>
<td align="left">2018-10-26</td>
<td align="left">2018-10-26 12:29:45</td>
<td align="left">result set description</td>
<td align="left">postgres</td>
<td align="left">172.17.0.2</td>
<td align="right">5432</td>
</tr>
</tbody>
</table>
<p>We will work only in the <code>dvdrental</code> database. To reduce scrolling back and forth in the tutorial, the only metadata column we will use is the <code>showing</code> column.</p>
</div>
</div>
<div id="which-schema" class="section level3">
<h3><span class="header-section-number">11.4.8</span> Which Schema?</h3>
<div id="htmlwidget-514d280a38cf86ead40b" style="width:672px;height:480px;" class="grViz html-widget"></div>
<script type="application/json" data-for="htmlwidget-514d280a38cf86ead40b">{"x":{"diagram":"\ndigraph DB_Environment {\n    graph [overlap = true, fontsize = 10, rankdir=LR, height= 10]\n\n    node [shape = box,fontname = Helvetica,fontcolor=blue]\n         Schemas;\n\n    node [shape = box,fontname = Helvetica,fontcolor=\"\"]\n        Servers; DBs; Tables;\n\n    edge [arrowhead = crow, tail = tee]       \n    Servers -> DBs -> Schemas -> Tables\n}\n","config":{"engine":"dot","options":null}},"evals":[],"jsHooks":[]}</script>
<p>In the code block below, we look at the <code>information_schema.table</code> which contains information about all the schemas and table/views within our dvdrental database. Databases can have one or more schemas, containers that hold tables or views. Schemas partition the database into big logical blocks of related data and/or applications. Schema names usually reflect an application or logically related data sets. Occasionally a DBA will set up a new schema named after a user. This is typically a sandbox environment.</p>
<div id="dplyr" class="section level4">
<h4><span class="header-section-number">11.4.8.1</span> dplyr</h4>
<table>
<thead>
<tr class="header">
<th align="left">In</th>
<th align="left">Dplyr.Function</th>
<th align="left">description</th>
<th align="left">SQL.Clause</th>
<th align="left">Notes</th>
<th align="left">Category</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">N</td>
<td align="left">group_by() ungroup()</td>
<td align="left">Objects exported from other packages</td>
<td align="left">GROUP BY no ungroup</td>
<td align="left"></td>
<td align="left">Basic single-table verbs</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<div id="sql_be_02database-schemas-from-ansi-standard-information_schema.tables" class="section level2">
<h2><span class="header-section-number">11.5</span> SQL_BE_02:Database Schemas from ANSI standard INFORMATION_SCHEMA.TABLES</h2>
<div class="sourceCode" id="cb182"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb182-1" data-line-number="1">SQL_BE_<span class="dv">02</span> &lt;-</a>
<a class="sourceLine" id="cb182-2" data-line-number="2"><span class="st">  </span>DBI<span class="op">::</span><span class="kw">dbGetQuery</span>(</a>
<a class="sourceLine" id="cb182-3" data-line-number="3">  con,</a>
<a class="sourceLine" id="cb182-4" data-line-number="4">  <span class="st">&quot;SELECT &#39;DB Schema tables and views&#39; showing</span></a>
<a class="sourceLine" id="cb182-5" data-line-number="5"><span class="st">          ,t.table_catalog DB</span></a>
<a class="sourceLine" id="cb182-6" data-line-number="6"><span class="st">          ,t.table_schema</span></a>
<a class="sourceLine" id="cb182-7" data-line-number="7"><span class="st">          ,COUNT(*) tbl_vws</span></a>
<a class="sourceLine" id="cb182-8" data-line-number="8"><span class="st">     FROM information_schema.tables t</span></a>
<a class="sourceLine" id="cb182-9" data-line-number="9"><span class="st">    GROUP BY t.table_catalog,t.table_schema</span></a>
<a class="sourceLine" id="cb182-10" data-line-number="10"><span class="st">  &quot;</span></a>
<a class="sourceLine" id="cb182-11" data-line-number="11">  )</a>
<a class="sourceLine" id="cb182-12" data-line-number="12"><span class="kw">display_rs</span>(MODE,SQL_BE_<span class="dv">02</span>,display_rows)</a></code></pre></div>
<table>
<thead>
<tr class="header">
<th align="left">showing</th>
<th align="left">db</th>
<th align="left">table_schema</th>
<th align="right">tbl_vws</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">DB Schema tables and views</td>
<td align="left">dvdrental</td>
<td align="left">pg_catalog</td>
<td align="right">121</td>
</tr>
<tr class="even">
<td align="left">DB Schema tables and views</td>
<td align="left">dvdrental</td>
<td align="left">public</td>
<td align="right">22</td>
</tr>
<tr class="odd">
<td align="left">DB Schema tables and views</td>
<td align="left">dvdrental</td>
<td align="left">information_schema</td>
<td align="right">67</td>
</tr>
</tbody>
</table>
<pre><code>*  What schemas are in the `dvdrental` database?
*  How many tables and/or views are in each schema?</code></pre>
<p>In the SQL-Quick Start section, we mentioned that SQL statements can either be detailed or grouped. SQL_BE_02 is our first example of a GROUPED statement. It has a GROUP BY clause:</p>
<pre><code>GROUP BY t.table_catalog,t.table_schema</code></pre>
<p>and an aggregation in the SELECT clause:</p>
<pre><code>COUNT(*) tbl_vws</code></pre>
<p>Every non-constant column in the SELECT CLAUSE that is not part of an aggregate function must be included in the group by clause. Note that the <code>showing</code> column, value ‘DB Schema tables and views’ is not included in the <code>GROUP BY</code> clause.</p>
<p>We see that there are three schemas. The pg_catalog is the standard PostgreSQL meta data and core schema. Postgres uses this schema to manage the internal workings of the database. DBA’s are the primary users of pg_catalog. We used the pg_catalog schema to answer the question ‘How many databases reside in the Docker Container?’, but normally the data analyst is not interested in analyzing database data.</p>
<p>The information_schema contains ANSI standardized views used across the different SQL vendors, (Oracle, Sysbase, MS SQL Server, IBM DB2, etc). The information_schema contains a plethora of metadata that will help you locate your data tables, understand the relationships between the tables, and write efficient SQL queries.</p>
<div id="exercises-1" class="section level3">
<h3><span class="header-section-number">11.5.1</span> Exercises</h3>
<p>In SQL_BE_02 we saw the most common aggregation form, one or more aggregate functions in the SELECT clause and a GROUP BY clause.</p>
</div>
</div>
<div id="sql_be_03group-by-no-aggregation-deduplication" class="section level2">
<h2><span class="header-section-number">11.6</span> SQL_BE_03:Group By No Aggregation – Deduplication</h2>
<div class="sourceCode" id="cb186"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb186-1" data-line-number="1">SQL_BE_<span class="dv">03</span> &lt;-</a>
<a class="sourceLine" id="cb186-2" data-line-number="2"><span class="st">  </span>DBI<span class="op">::</span><span class="kw">dbGetQuery</span>(</a>
<a class="sourceLine" id="cb186-3" data-line-number="3">  con,</a>
<a class="sourceLine" id="cb186-4" data-line-number="4">  <span class="st">&quot;SELECT &#39;DB Schemas&#39; showing</span></a>
<a class="sourceLine" id="cb186-5" data-line-number="5"><span class="st">          ,t.table_catalog DB</span></a>
<a class="sourceLine" id="cb186-6" data-line-number="6"><span class="st">          ,t.table_schema</span></a>
<a class="sourceLine" id="cb186-7" data-line-number="7"><span class="st">          ,COUNT(*) tbl_vws  -- delete or comment this line out</span></a>
<a class="sourceLine" id="cb186-8" data-line-number="8"><span class="st">     FROM information_schema.tables t</span></a>
<a class="sourceLine" id="cb186-9" data-line-number="9"><span class="st">    GROUP BY t.table_catalog,t.table_schema</span></a>
<a class="sourceLine" id="cb186-10" data-line-number="10"><span class="st">  &quot;</span></a>
<a class="sourceLine" id="cb186-11" data-line-number="11">  )</a>
<a class="sourceLine" id="cb186-12" data-line-number="12"><span class="kw">kable</span>(<span class="kw">head</span>(SQL_BE_<span class="dv">03</span>,display_rows))</a></code></pre></div>
<table>
<thead>
<tr class="header">
<th align="left">showing</th>
<th align="left">db</th>
<th align="left">table_schema</th>
<th align="right">tbl_vws</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">DB Schemas</td>
<td align="left">dvdrental</td>
<td align="left">pg_catalog</td>
<td align="right">121</td>
</tr>
<tr class="even">
<td align="left">DB Schemas</td>
<td align="left">dvdrental</td>
<td align="left">public</td>
<td align="right">22</td>
</tr>
<tr class="odd">
<td align="left">DB Schemas</td>
<td align="left">dvdrental</td>
<td align="left">information_schema</td>
<td align="right">67</td>
</tr>
</tbody>
</table>
<pre><code>*  What is the net effect?</code></pre>
<p>You have basically created a de-duped list, a distinct list. Normally one needs to know why there are duplicates in the data and get them cleaned up before proceeding.</p>
</div>
<div id="sql_be_04distinct-list-take-2" class="section level2">
<h2><span class="header-section-number">11.7</span> SQL_BE_04:Distinct list take 2</h2>
<div class="sourceCode" id="cb188"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb188-1" data-line-number="1"><span class="co"># DISTINCT clause dedupe the list</span></a>
<a class="sourceLine" id="cb188-2" data-line-number="2">SQL_BE_<span class="dv">04</span> &lt;-</a>
<a class="sourceLine" id="cb188-3" data-line-number="3"><span class="st">  </span>DBI<span class="op">::</span><span class="kw">dbGetQuery</span>(</a>
<a class="sourceLine" id="cb188-4" data-line-number="4">  con,</a>
<a class="sourceLine" id="cb188-5" data-line-number="5">  <span class="st">&quot;SELECT &#39;DB Schemas-distinct&#39; showing  -- add DISTINCT after SELECT</span></a>
<a class="sourceLine" id="cb188-6" data-line-number="6"><span class="st">          ,t.table_catalog DB </span></a>
<a class="sourceLine" id="cb188-7" data-line-number="7"><span class="st">          ,t.table_schema </span></a>
<a class="sourceLine" id="cb188-8" data-line-number="8"><span class="st">     FROM information_schema.tables t</span></a>
<a class="sourceLine" id="cb188-9" data-line-number="9"><span class="st">  &quot;</span></a>
<a class="sourceLine" id="cb188-10" data-line-number="10">  )</a>
<a class="sourceLine" id="cb188-11" data-line-number="11"><span class="kw">kable</span>(<span class="kw">head</span>(SQL_BE_<span class="dv">04</span>,display_rows<span class="op">+</span><span class="dv">10</span>))</a></code></pre></div>
<table>
<thead>
<tr class="header">
<th align="left">showing</th>
<th align="left">db</th>
<th align="left">table_schema</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">DB Schemas-distinct</td>
<td align="left">dvdrental</td>
<td align="left">public</td>
</tr>
<tr class="even">
<td align="left">DB Schemas-distinct</td>
<td align="left">dvdrental</td>
<td align="left">public</td>
</tr>
<tr class="odd">
<td align="left">DB Schemas-distinct</td>
<td align="left">dvdrental</td>
<td align="left">public</td>
</tr>
<tr class="even">
<td align="left">DB Schemas-distinct</td>
<td align="left">dvdrental</td>
<td align="left">public</td>
</tr>
<tr class="odd">
<td align="left">DB Schemas-distinct</td>
<td align="left">dvdrental</td>
<td align="left">public</td>
</tr>
<tr class="even">
<td align="left">DB Schemas-distinct</td>
<td align="left">dvdrental</td>
<td align="left">public</td>
</tr>
<tr class="odd">
<td align="left">DB Schemas-distinct</td>
<td align="left">dvdrental</td>
<td align="left">pg_catalog</td>
</tr>
<tr class="even">
<td align="left">DB Schemas-distinct</td>
<td align="left">dvdrental</td>
<td align="left">pg_catalog</td>
</tr>
<tr class="odd">
<td align="left">DB Schemas-distinct</td>
<td align="left">dvdrental</td>
<td align="left">public</td>
</tr>
<tr class="even">
<td align="left">DB Schemas-distinct</td>
<td align="left">dvdrental</td>
<td align="left">public</td>
</tr>
<tr class="odd">
<td align="left">DB Schemas-distinct</td>
<td align="left">dvdrental</td>
<td align="left">public</td>
</tr>
<tr class="even">
<td align="left">DB Schemas-distinct</td>
<td align="left">dvdrental</td>
<td align="left">public</td>
</tr>
<tr class="odd">
<td align="left">DB Schemas-distinct</td>
<td align="left">dvdrental</td>
<td align="left">public</td>
</tr>
<tr class="even">
<td align="left">DB Schemas-distinct</td>
<td align="left">dvdrental</td>
<td align="left">public</td>
</tr>
<tr class="odd">
<td align="left">DB Schemas-distinct</td>
<td align="left">dvdrental</td>
<td align="left">public</td>
</tr>
<tr class="even">
<td align="left">DB Schemas-distinct</td>
<td align="left">dvdrental</td>
<td align="left">public</td>
</tr>
<tr class="odd">
<td align="left">DB Schemas-distinct</td>
<td align="left">dvdrental</td>
<td align="left">public</td>
</tr>
<tr class="even">
<td align="left">DB Schemas-distinct</td>
<td align="left">dvdrental</td>
<td align="left">public</td>
</tr>
<tr class="odd">
<td align="left">DB Schemas-distinct</td>
<td align="left">dvdrental</td>
<td align="left">public</td>
</tr>
<tr class="even">
<td align="left">DB Schemas-distinct</td>
<td align="left">dvdrental</td>
<td align="left">public</td>
</tr>
</tbody>
</table>
<pre><code>*  How many distinct rows did you get?  Should be 3.</code></pre>
</div>
<div id="sql_be_05---how-to-drill-down-and-aggregate-at-lower-level" class="section level2">
<h2><span class="header-section-number">11.8</span> SQL_BE_05 - How to Drill Down and Aggregate at Lower Level</h2>
<p>In SQL_BE_02 we created a list of the number of objects in each schema and labeled it <code>tbl_vws</code>. To avoid retyping column names, one often just copies and pastes the necessary columns from the SELECT clause into the <code>GROUP BY</code> clause.</p>
<div class="sourceCode" id="cb190"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb190-1" data-line-number="1"><span class="co">#SQL_BE_05:drilling down from table_schema to table_type</span></a>
<a class="sourceLine" id="cb190-2" data-line-number="2">SQL_BE_<span class="dv">05</span> &lt;-</a>
<a class="sourceLine" id="cb190-3" data-line-number="3"><span class="st">  </span>DBI<span class="op">::</span><span class="kw">dbGetQuery</span>(</a>
<a class="sourceLine" id="cb190-4" data-line-number="4">  con,</a>
<a class="sourceLine" id="cb190-5" data-line-number="5">  <span class="st">&quot;SELECT &#39;GROUP BY t.table_catalog,t.table_schema&#39; showing  </span></a>
<a class="sourceLine" id="cb190-6" data-line-number="6"><span class="st">          ,t.table_catalog DB </span></a>
<a class="sourceLine" id="cb190-7" data-line-number="7"><span class="st">          ,t.table_schema </span></a>
<a class="sourceLine" id="cb190-8" data-line-number="8"><span class="st">          -- add the new drill down column table_type here --</span></a>
<a class="sourceLine" id="cb190-9" data-line-number="9"><span class="st">          --,COUNT(*) count --uncomment this line to add the aggregate function</span></a>
<a class="sourceLine" id="cb190-10" data-line-number="10"><span class="st">     FROM information_schema.tables t</span></a>
<a class="sourceLine" id="cb190-11" data-line-number="11"><span class="st">    --uncomment following line and copy and paste the necessary columns from the SELECT clause</span></a>
<a class="sourceLine" id="cb190-12" data-line-number="12"><span class="st">    --GROUP BY </span></a>
<a class="sourceLine" id="cb190-13" data-line-number="13"><span class="st">  &quot;</span></a>
<a class="sourceLine" id="cb190-14" data-line-number="14">  )</a>
<a class="sourceLine" id="cb190-15" data-line-number="15"><span class="kw">kable</span>(<span class="kw">head</span>(SQL_BE_<span class="dv">05</span>,display_rows))</a></code></pre></div>
<table>
<thead>
<tr class="header">
<th align="left">showing</th>
<th align="left">db</th>
<th align="left">table_schema</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">GROUP BY t.table_catalog,t.table_schema</td>
<td align="left">dvdrental</td>
<td align="left">public</td>
</tr>
<tr class="even">
<td align="left">GROUP BY t.table_catalog,t.table_schema</td>
<td align="left">dvdrental</td>
<td align="left">public</td>
</tr>
<tr class="odd">
<td align="left">GROUP BY t.table_catalog,t.table_schema</td>
<td align="left">dvdrental</td>
<td align="left">public</td>
</tr>
<tr class="even">
<td align="left">GROUP BY t.table_catalog,t.table_schema</td>
<td align="left">dvdrental</td>
<td align="left">public</td>
</tr>
<tr class="odd">
<td align="left">GROUP BY t.table_catalog,t.table_schema</td>
<td align="left">dvdrental</td>
<td align="left">public</td>
</tr>
<tr class="even">
<td align="left">GROUP BY t.table_catalog,t.table_schema</td>
<td align="left">dvdrental</td>
<td align="left">public</td>
</tr>
<tr class="odd">
<td align="left">GROUP BY t.table_catalog,t.table_schema</td>
<td align="left">dvdrental</td>
<td align="left">pg_catalog</td>
</tr>
<tr class="even">
<td align="left">GROUP BY t.table_catalog,t.table_schema</td>
<td align="left">dvdrental</td>
<td align="left">pg_catalog</td>
</tr>
<tr class="odd">
<td align="left">GROUP BY t.table_catalog,t.table_schema</td>
<td align="left">dvdrental</td>
<td align="left">public</td>
</tr>
<tr class="even">
<td align="left">GROUP BY t.table_catalog,t.table_schema</td>
<td align="left">dvdrental</td>
<td align="left">public</td>
</tr>
</tbody>
</table>
<pre><code>*  How many rows were returned?
*  Which schemas have more views than tables?
*  Which schemas have more tables than views?</code></pre>
<pre><code>SQL-BE-STINGER_02: GROUP BY STINGERS

In the previous exercise: 
1.  if you copied the SELECT columns directly into the 

    GROUP BY &#39;DB Schemas-table types&#39; showing
             ,t.table_catalog DB 
             ,t.table_schema 
             ,table_type 

    You got an &#39;ERROR: syntax error at or near &quot;showing&quot;&#39; 
    Fix: Do not include the constant derived column values in the GROUP BY

2.  if you copied the SELECT columns directly into the

    GROUP BY ,t.table_catalog DB 
             ,t.table_schema 
             ,table_type 
             
    You got an &#39;ERROR: syntax error at or near &quot;,&quot;&#39;  
    Fix: The first column in the GROUP BY clause cannot begin with a comma, &#39;,&#39;, an easy copy and paste mistake.
    
3.  if you copied the SELECT columns directly into the

    GROUP BY t.table_catalog DB 
             ,t.table_schema 
             ,table_type     

    You got an &#39;ERROR: syntax error at or near &quot;DB&quot;&#39;
    Fix: The GROUP BY clause wants the actual column name, NOT the column name and alias.  This is the most common STINGER of the three, especially if one has a large set of group by columns.
</code></pre>
</div>
<div id="sql_be_06---how-to-filter-groups" class="section level2">
<h2><span class="header-section-number">11.9</span> SQL_BE_06 - How to FILTER GROUPS</h2>
<p>In the SQL Quick Start Section we looked at the SQL SELECT detail statement and used the WHERE clause to filter which detail rows that get returned. In the following exercise, we look at filtering which GROUPS get returned.</p>
<p>Instructions:</p>
<ol style="list-style-type: decimal">
<li>Execute the code block before modifying it to see the counts associated with each group.</li>
<li>Answer the before question(s) that follow the code block.</li>
<li>See the comment above the HAVING clause in the code block and modify the code block accordingly.</li>
<li>Answer the after question(s) that follow the code block.</li>
</ol>
<div class="sourceCode" id="cb193"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb193-1" data-line-number="1"><span class="co">#SQL_BE_06: GROUP BY FILTERING</span></a>
<a class="sourceLine" id="cb193-2" data-line-number="2">SQL_BE_<span class="dv">06</span> &lt;-</a>
<a class="sourceLine" id="cb193-3" data-line-number="3"><span class="st">  </span>DBI<span class="op">::</span><span class="kw">dbGetQuery</span>(</a>
<a class="sourceLine" id="cb193-4" data-line-number="4">  con,</a>
<a class="sourceLine" id="cb193-5" data-line-number="5">  <span class="st">&quot;SELECT &#39;HAVING COUNT(*) BETWEEN 5 and 20 or COUNT(*) &gt; 60&#39; showing  </span></a>
<a class="sourceLine" id="cb193-6" data-line-number="6"><span class="st">          ,t.table_catalog DB </span></a>
<a class="sourceLine" id="cb193-7" data-line-number="7"><span class="st">          ,t.table_schema </span></a>
<a class="sourceLine" id="cb193-8" data-line-number="8"><span class="st">          ,table_type</span></a>
<a class="sourceLine" id="cb193-9" data-line-number="9"><span class="st">          ,COUNT(*) count </span></a>
<a class="sourceLine" id="cb193-10" data-line-number="10"><span class="st">     FROM information_schema.tables t</span></a>
<a class="sourceLine" id="cb193-11" data-line-number="11"><span class="st">    GROUP BY t.table_catalog </span></a>
<a class="sourceLine" id="cb193-12" data-line-number="12"><span class="st">          ,t.table_schema </span></a>
<a class="sourceLine" id="cb193-13" data-line-number="13"><span class="st">          ,table_type</span></a>
<a class="sourceLine" id="cb193-14" data-line-number="14"><span class="st">    /* uncomment the following line and return all groups that have a count </span></a>
<a class="sourceLine" id="cb193-15" data-line-number="15"><span class="st">       between 5 and 20 or a COUNT &gt; 60</span></a>
<a class="sourceLine" id="cb193-16" data-line-number="16"><span class="st">    */</span></a>
<a class="sourceLine" id="cb193-17" data-line-number="17"><span class="st">    --HAVING COUNT(*) BETWEEN X and Y or COUNT(*) &gt; Z</span></a>
<a class="sourceLine" id="cb193-18" data-line-number="18"><span class="st">  &quot;</span>  )</a>
<a class="sourceLine" id="cb193-19" data-line-number="19"><span class="kw">kable</span>(<span class="kw">head</span>(SQL_BE_<span class="dv">06</span>,display_rows))</a></code></pre></div>
<table>
<thead>
<tr class="header">
<th align="left">showing</th>
<th align="left">db</th>
<th align="left">table_schema</th>
<th align="left">table_type</th>
<th align="right">count</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">HAVING COUNT(<em>) BETWEEN 5 and 20 or COUNT(</em>) &gt; 60</td>
<td align="left">dvdrental</td>
<td align="left">information_schema</td>
<td align="left">BASE TABLE</td>
<td align="right">7</td>
</tr>
<tr class="even">
<td align="left">HAVING COUNT(<em>) BETWEEN 5 and 20 or COUNT(</em>) &gt; 60</td>
<td align="left">dvdrental</td>
<td align="left">information_schema</td>
<td align="left">VIEW</td>
<td align="right">60</td>
</tr>
<tr class="odd">
<td align="left">HAVING COUNT(<em>) BETWEEN 5 and 20 or COUNT(</em>) &gt; 60</td>
<td align="left">dvdrental</td>
<td align="left">pg_catalog</td>
<td align="left">BASE TABLE</td>
<td align="right">62</td>
</tr>
<tr class="even">
<td align="left">HAVING COUNT(<em>) BETWEEN 5 and 20 or COUNT(</em>) &gt; 60</td>
<td align="left">dvdrental</td>
<td align="left">public</td>
<td align="left">BASE TABLE</td>
<td align="right">15</td>
</tr>
<tr class="odd">
<td align="left">HAVING COUNT(<em>) BETWEEN 5 and 20 or COUNT(</em>) &gt; 60</td>
<td align="left">dvdrental</td>
<td align="left">public</td>
<td align="left">VIEW</td>
<td align="right">7</td>
</tr>
<tr class="even">
<td align="left">HAVING COUNT(<em>) BETWEEN 5 and 20 or COUNT(</em>) &gt; 60</td>
<td align="left">dvdrental</td>
<td align="left">pg_catalog</td>
<td align="left">VIEW</td>
<td align="right">59</td>
</tr>
</tbody>
</table>
<p>Before Questions:</p>
<pre><code>*  How many groups are there before modifying the code block?
*  How many table types have counts between 5 and 20?
*  How many table types have counts greater than 60? </code></pre>
<p>After Questions:</p>
<pre><code>*  How many groups are there after modifying the code block?
*  Did the code block return the rows identified in the before questions?</code></pre>
<p>The key difference between WHERE and HAVING filtering is scope. WHERE filters at the row level and HAVING filters at the GROUP BY level.</p>
<p>In practice, WHERE filters can be very simple to very complex, but HAVING filters are rarely compound conditional statements. Common applications of the HAVING clause is to identify duplicate data.</p>
</div>
<div id="sql_be_07---how-to-order-result-set-on-a-single-column" class="section level2">
<h2><span class="header-section-number">11.10</span> SQL_BE_07 - HOW to ORDER Result Set on a Single Column</h2>
<p>There is one final SQL SELECT clause, the <code>ORDER BY</code> clause which can be used with either a detail or aggregate SQL statement. In SQL_BE_05 we drilled down and counted the different table types in the different schemas.</p>
<p>In SQL_BE_07, we add a single level ORDER BY clause. Execute the following code block before adding the ORDER BY clause.</p>
<ol style="list-style-type: decimal">
<li>Is the output sorted by the <code>table_schema</code>? It maybe or may not be? Remember that SQL returns result sets and doesn’t guarantee that the result set is always returned in the same order without an explicit <code>ORDER BY</code> clause.</li>
</ol>
<div class="sourceCode" id="cb196"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb196-1" data-line-number="1"><span class="co">#SQL_BE_07: SORT BY CLAUSE</span></a>
<a class="sourceLine" id="cb196-2" data-line-number="2">SQL_BE_<span class="dv">07</span> &lt;-</a>
<a class="sourceLine" id="cb196-3" data-line-number="3"><span class="st">  </span>DBI<span class="op">::</span><span class="kw">dbGetQuery</span>(</a>
<a class="sourceLine" id="cb196-4" data-line-number="4">  con,</a>
<a class="sourceLine" id="cb196-5" data-line-number="5">  <span class="st">&quot;SELECT &#39;ORDER BY t.table_schema&#39; showing  </span></a>
<a class="sourceLine" id="cb196-6" data-line-number="6"><span class="st">          ,t.table_catalog DB </span></a>
<a class="sourceLine" id="cb196-7" data-line-number="7"><span class="st">          ,t.table_schema </span></a>
<a class="sourceLine" id="cb196-8" data-line-number="8"><span class="st">          ,table_type</span></a>
<a class="sourceLine" id="cb196-9" data-line-number="9"><span class="st">          ,COUNT(*) count </span></a>
<a class="sourceLine" id="cb196-10" data-line-number="10"><span class="st">     FROM information_schema.tables t</span></a>
<a class="sourceLine" id="cb196-11" data-line-number="11"><span class="st">    GROUP BY t.table_catalog </span></a>
<a class="sourceLine" id="cb196-12" data-line-number="12"><span class="st">          ,t.table_schema </span></a>
<a class="sourceLine" id="cb196-13" data-line-number="13"><span class="st">          ,t.table_type</span></a>
<a class="sourceLine" id="cb196-14" data-line-number="14"><span class="st">    -- add an ORDER BY table schema clause here--</span></a>
<a class="sourceLine" id="cb196-15" data-line-number="15"><span class="st">  &quot;</span>  )</a>
<a class="sourceLine" id="cb196-16" data-line-number="16"><span class="kw">kable</span>(<span class="kw">head</span>(SQL_BE_<span class="dv">07</span>,display_rows))</a></code></pre></div>
<table>
<thead>
<tr class="header">
<th align="left">showing</th>
<th align="left">db</th>
<th align="left">table_schema</th>
<th align="left">table_type</th>
<th align="right">count</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">ORDER BY t.table_schema</td>
<td align="left">dvdrental</td>
<td align="left">information_schema</td>
<td align="left">BASE TABLE</td>
<td align="right">7</td>
</tr>
<tr class="even">
<td align="left">ORDER BY t.table_schema</td>
<td align="left">dvdrental</td>
<td align="left">information_schema</td>
<td align="left">VIEW</td>
<td align="right">60</td>
</tr>
<tr class="odd">
<td align="left">ORDER BY t.table_schema</td>
<td align="left">dvdrental</td>
<td align="left">pg_catalog</td>
<td align="left">BASE TABLE</td>
<td align="right">62</td>
</tr>
<tr class="even">
<td align="left">ORDER BY t.table_schema</td>
<td align="left">dvdrental</td>
<td align="left">public</td>
<td align="left">BASE TABLE</td>
<td align="right">15</td>
</tr>
<tr class="odd">
<td align="left">ORDER BY t.table_schema</td>
<td align="left">dvdrental</td>
<td align="left">public</td>
<td align="left">VIEW</td>
<td align="right">7</td>
</tr>
<tr class="even">
<td align="left">ORDER BY t.table_schema</td>
<td align="left">dvdrental</td>
<td align="left">pg_catalog</td>
<td align="left">VIEW</td>
<td align="right">59</td>
</tr>
</tbody>
</table>
</div>
<div id="sql_be_08---how-to-order-result-set-on-a-multiple-columns-and-descending-order" class="section level2">
<h2><span class="header-section-number">11.11</span> SQL_BE_08 - HOW to ORDER Result Set on a Multiple Columns and Descending Order</h2>
<p>In SQL_BE_08, we add another level to the ORDER BY clause with two levels table_type and counts in descending order. Execute the following code block before updating the ORDER BY clause.</p>
<ol style="list-style-type: decimal">
<li>Is the output for each group sorted in descending order? Some groups maybe or may not be sorted in descending order?</li>
</ol>
<div class="sourceCode" id="cb197"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb197-1" data-line-number="1"><span class="co">#SQL_BE_08: SORT BY CLAUSE</span></a>
<a class="sourceLine" id="cb197-2" data-line-number="2">SQL_BE_<span class="dv">08</span> &lt;-</a>
<a class="sourceLine" id="cb197-3" data-line-number="3"><span class="st">  </span>DBI<span class="op">::</span><span class="kw">dbGetQuery</span>(</a>
<a class="sourceLine" id="cb197-4" data-line-number="4">  con,</a>
<a class="sourceLine" id="cb197-5" data-line-number="5">  <span class="st">&quot;SELECT &#39;ORDER BY table_schema, count(*) desc&#39; showing  </span></a>
<a class="sourceLine" id="cb197-6" data-line-number="6"><span class="st">          ,t.table_catalog DB </span></a>
<a class="sourceLine" id="cb197-7" data-line-number="7"><span class="st">          ,t.table_schema </span></a>
<a class="sourceLine" id="cb197-8" data-line-number="8"><span class="st">          ,table_type</span></a>
<a class="sourceLine" id="cb197-9" data-line-number="9"><span class="st">          ,COUNT(*) count </span></a>
<a class="sourceLine" id="cb197-10" data-line-number="10"><span class="st">     FROM information_schema.tables t</span></a>
<a class="sourceLine" id="cb197-11" data-line-number="11"><span class="st">    GROUP BY t.table_catalog </span></a>
<a class="sourceLine" id="cb197-12" data-line-number="12"><span class="st">          ,t.table_schema </span></a>
<a class="sourceLine" id="cb197-13" data-line-number="13"><span class="st">          ,t.table_type</span></a>
<a class="sourceLine" id="cb197-14" data-line-number="14"><span class="st">    -- Update the ORDER BY clause with the counts in descending order --</span></a>
<a class="sourceLine" id="cb197-15" data-line-number="15"><span class="st">    ORDER BY t.table_schema</span></a>
<a class="sourceLine" id="cb197-16" data-line-number="16"><span class="st">  &quot;</span>  )</a>
<a class="sourceLine" id="cb197-17" data-line-number="17"><span class="kw">kable</span>(<span class="kw">head</span>(SQL_BE_<span class="dv">08</span>,display_rows))</a></code></pre></div>
<table>
<thead>
<tr class="header">
<th align="left">showing</th>
<th align="left">db</th>
<th align="left">table_schema</th>
<th align="left">table_type</th>
<th align="right">count</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">ORDER BY table_schema, count(*) desc</td>
<td align="left">dvdrental</td>
<td align="left">information_schema</td>
<td align="left">BASE TABLE</td>
<td align="right">7</td>
</tr>
<tr class="even">
<td align="left">ORDER BY table_schema, count(*) desc</td>
<td align="left">dvdrental</td>
<td align="left">information_schema</td>
<td align="left">VIEW</td>
<td align="right">60</td>
</tr>
<tr class="odd">
<td align="left">ORDER BY table_schema, count(*) desc</td>
<td align="left">dvdrental</td>
<td align="left">pg_catalog</td>
<td align="left">BASE TABLE</td>
<td align="right">62</td>
</tr>
<tr class="even">
<td align="left">ORDER BY table_schema, count(*) desc</td>
<td align="left">dvdrental</td>
<td align="left">pg_catalog</td>
<td align="left">VIEW</td>
<td align="right">59</td>
</tr>
<tr class="odd">
<td align="left">ORDER BY table_schema, count(*) desc</td>
<td align="left">dvdrental</td>
<td align="left">public</td>
<td align="left">BASE TABLE</td>
<td align="right">15</td>
</tr>
<tr class="even">
<td align="left">ORDER BY table_schema, count(*) desc</td>
<td align="left">dvdrental</td>
<td align="left">public</td>
<td align="left">VIEW</td>
<td align="right">7</td>
</tr>
</tbody>
</table>
<p>Note that the ORDER BY clause either references the column name table_schema, or the aggregate function count(*).</p>
<pre><code>SQL-BE-STINGER_03: ORDER BY column position

THE ORDER BY clause is an odd duck because all the other clauses either refer to a column name or derived value.  The ORDER BY clause also allows one to reference the column by their numeric sequence in the list.  
The ORDER BY clause could have been written as 

    ORDER BY 3, 5 desc
    
The big time stinger comes when additional columns are added to the `SELECT` clause and the result set is no longer sorted as expected.  Don&#39;t be lazy, always explcitly list the `ORDER BY` values by name, not position to avoid the big time stinger.
</code></pre>
<div id="table-and-column-data-metadata" class="section level3">
<h3><span class="header-section-number">11.11.1</span> Table and Column Data – MetaData</h3>
<p>Database user applications keep track of user application data. The database itself is a special application and has its own schemas, information_schema and pg_catalog which it maintains to monitor the state of the database itself and user application data, the <code>dvdrental</code> application in the <code>public</code> schema. In Docker Installation section, Postgres database application was installed and then the user database <code>dvdrental</code> was installed. The <code>dvdrental</code> database objects reside in the public schema and the database knows about and tracks them in the <code>information_schema</code> and the <code>pg_catalog</code> schemas. In the next couple of SQL_BE’s, we will ignore the <code>pg_catalog</code>.</p>
<div id="sql-like-and-string-wildcards" class="section level4">
<h4><span class="header-section-number">11.11.1.1</span> SQL LIKE and String Wildcards</h4>
<p>SQL recognizes two string wildcard characters, ’_’ and ‘%’, any single character and any string of characters including a 0 length string. To perform more advance string searches and manipulation, one needs regular expressions.</p>
<table>
<colgroup>
<col width="23%" />
<col width="76%" />
</colgroup>
<thead>
<tr class="header">
<th>LIKE</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>where table_name like ‘table%’</td>
<td>find rows where table_name begins with ‘table’.</td>
</tr>
<tr class="even">
<td>where table_name like ‘table_’</td>
<td>find rows where table_name begins with ‘table’ followed by any single character, e.g. ‘tables’</td>
</tr>
<tr class="odd">
<td>where table_name like ‘%usage’</td>
<td>find rows where table_name ends with ‘usage’</td>
</tr>
<tr class="even">
<td>where table_name like ‘%col%’</td>
<td>find rows where ‘col’ is anywhere in table_name.</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<div id="sql_be_09-looks-for-table-metadata-just-in-the-information_schema." class="section level2">
<h2><span class="header-section-number">11.12</span> SQL_BE_09 looks for table metadata just in the information_schema.</h2>
<div class="sourceCode" id="cb199"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb199-1" data-line-number="1"><span class="co">#SQL_BE_09: Table Metadata</span></a>
<a class="sourceLine" id="cb199-2" data-line-number="2">SQL_BE_<span class="dv">09</span> &lt;-</a>
<a class="sourceLine" id="cb199-3" data-line-number="3"><span class="st">  </span>DBI<span class="op">::</span><span class="kw">dbGetQuery</span>(</a>
<a class="sourceLine" id="cb199-4" data-line-number="4">  con,</a>
<a class="sourceLine" id="cb199-5" data-line-number="5">  <span class="st">&quot;SELECT &#39;SQL_BE_09 SQL Order of Precedence&#39; SQL_BE</span></a>
<a class="sourceLine" id="cb199-6" data-line-number="6"><span class="st">          ,table_catalog || &#39;.&#39; || table_schema db_info     </span></a>
<a class="sourceLine" id="cb199-7" data-line-number="7"><span class="st">          ,table_type</span></a>
<a class="sourceLine" id="cb199-8" data-line-number="8"><span class="st">          ,table_name</span></a>
<a class="sourceLine" id="cb199-9" data-line-number="9"><span class="st">         ,&#39;table_schema = &#39;&#39;information_schema&#39;&#39; AND &#39;||</span></a>
<a class="sourceLine" id="cb199-10" data-line-number="10"><span class="st">          &#39;table_name like &#39;&#39;table%&#39;&#39; and table_type = &#39;&#39;VIEW&#39;&#39;&#39; showing  </span></a>
<a class="sourceLine" id="cb199-11" data-line-number="11"><span class="st">     FROM information_schema.tables t</span></a>
<a class="sourceLine" id="cb199-12" data-line-number="12"><span class="st">   -- add a where clause to check the information_schema for any table_name </span></a>
<a class="sourceLine" id="cb199-13" data-line-number="13"><span class="st">   -- that begins with &#39;table&#39; any where in the name</span></a>
<a class="sourceLine" id="cb199-14" data-line-number="14"><span class="st">   -- and and has a table_type = VIEW</span></a>
<a class="sourceLine" id="cb199-15" data-line-number="15"><span class="st">    where table_schema = &#39;information_schema&#39;</span></a>
<a class="sourceLine" id="cb199-16" data-line-number="16"><span class="st">      and table_name like &#39;table%&#39; </span></a>
<a class="sourceLine" id="cb199-17" data-line-number="17"><span class="st">      and table_type = &#39;VIEW&#39;</span></a>
<a class="sourceLine" id="cb199-18" data-line-number="18"><span class="st">    ORDER BY table_type</span></a>
<a class="sourceLine" id="cb199-19" data-line-number="19"><span class="st">  &quot;</span>  )</a>
<a class="sourceLine" id="cb199-20" data-line-number="20"><span class="kw">display_rs</span>(MODE,SQL_BE_<span class="dv">09</span>,display_rows)</a></code></pre></div>
<table>
<thead>
<tr class="header">
<th align="left">sql_be</th>
<th align="left">db_info</th>
<th align="left">table_type</th>
<th align="left">table_name</th>
<th align="left">showing</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">SQL_BE_09 SQL Order of Precedence</td>
<td align="left">dvdrental.information_schema</td>
<td align="left">VIEW</td>
<td align="left">table_constraints</td>
<td align="left">table_schema = ‘information_schema’ AND table_name like ‘table%’ and table_type = ‘VIEW’</td>
</tr>
<tr class="even">
<td align="left">SQL_BE_09 SQL Order of Precedence</td>
<td align="left">dvdrental.information_schema</td>
<td align="left">VIEW</td>
<td align="left">table_privileges</td>
<td align="left">table_schema = ‘information_schema’ AND table_name like ‘table%’ and table_type = ‘VIEW’</td>
</tr>
<tr class="odd">
<td align="left">SQL_BE_09 SQL Order of Precedence</td>
<td align="left">dvdrental.information_schema</td>
<td align="left">VIEW</td>
<td align="left">tables</td>
<td align="left">table_schema = ‘information_schema’ AND table_name like ‘table%’ and table_type = ‘VIEW’</td>
</tr>
</tbody>
</table>
<pre><code>*  How many rows are in the result set?</code></pre>
</div>
<div id="sql_be_10-column-metadata" class="section level2">
<h2><span class="header-section-number">11.13</span> SQL_BE_10: Column Metadata</h2>
<p>In the next SQL_BE, we look for column metadata tables.</p>
<div class="sourceCode" id="cb201"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb201-1" data-line-number="1">## SQL_BE_10: Column Metadata</a>
<a class="sourceLine" id="cb201-2" data-line-number="2">SQL_BE_<span class="dv">10</span> &lt;-</a>
<a class="sourceLine" id="cb201-3" data-line-number="3"><span class="st">  </span>DBI<span class="op">::</span><span class="kw">dbGetQuery</span>(</a>
<a class="sourceLine" id="cb201-4" data-line-number="4">  con,</a>
<a class="sourceLine" id="cb201-5" data-line-number="5">  <span class="st">&quot;SELECT &#39;SQL_BE_10 SQL Order of Precedence&#39; SQL_BE</span></a>
<a class="sourceLine" id="cb201-6" data-line-number="6"><span class="st">          ,table_catalog || &#39;.&#39; || table_schema db_info  </span></a>
<a class="sourceLine" id="cb201-7" data-line-number="7"><span class="st">          ,table_type</span></a>
<a class="sourceLine" id="cb201-8" data-line-number="8"><span class="st">          ,table_name</span></a>
<a class="sourceLine" id="cb201-9" data-line-number="9"><span class="st">         ,&#39;table_schema = &#39;&#39;information_schema&#39;&#39; AND &#39;||</span></a>
<a class="sourceLine" id="cb201-10" data-line-number="10"><span class="st">          &#39;table_name like &#39;&#39;%col%&#39;&#39; and table_type = &#39;&#39;VIEW&#39;&#39;&#39; showing </span></a>
<a class="sourceLine" id="cb201-11" data-line-number="11"><span class="st">     FROM information_schema.tables t</span></a>
<a class="sourceLine" id="cb201-12" data-line-number="12"><span class="st">   -- add a where clause to return any table_name that contains &#39;col&#39; any where in the name</span></a>
<a class="sourceLine" id="cb201-13" data-line-number="13"><span class="st">    where table_schema = &#39;information_schema&#39;</span></a>
<a class="sourceLine" id="cb201-14" data-line-number="14"><span class="st">      and table_name like &#39;%col%&#39; </span></a>
<a class="sourceLine" id="cb201-15" data-line-number="15"><span class="st">      and table_type = &#39;VIEW&#39;</span></a>
<a class="sourceLine" id="cb201-16" data-line-number="16"><span class="st">    ORDER BY table_type</span></a>
<a class="sourceLine" id="cb201-17" data-line-number="17"><span class="st">  &quot;</span>  )</a>
<a class="sourceLine" id="cb201-18" data-line-number="18"><span class="kw">display_rs</span>(MODE,SQL_BE_<span class="dv">10</span>,display_rows)</a></code></pre></div>
<table>
<thead>
<tr class="header">
<th align="left">sql_be</th>
<th align="left">db_info</th>
<th align="left">table_type</th>
<th align="left">table_name</th>
<th align="left">showing</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">SQL_BE_10 SQL Order of Precedence</td>
<td align="left">dvdrental.information_schema</td>
<td align="left">VIEW</td>
<td align="left">collations</td>
<td align="left">table_schema = ‘information_schema’ AND table_name like ‘%col%’ and table_type = ‘VIEW’</td>
</tr>
<tr class="even">
<td align="left">SQL_BE_10 SQL Order of Precedence</td>
<td align="left">dvdrental.information_schema</td>
<td align="left">VIEW</td>
<td align="left">collation_character_set_applicability</td>
<td align="left">table_schema = ‘information_schema’ AND table_name like ‘%col%’ and table_type = ‘VIEW’</td>
</tr>
<tr class="odd">
<td align="left">SQL_BE_10 SQL Order of Precedence</td>
<td align="left">dvdrental.information_schema</td>
<td align="left">VIEW</td>
<td align="left">column_domain_usage</td>
<td align="left">table_schema = ‘information_schema’ AND table_name like ‘%col%’ and table_type = ‘VIEW’</td>
</tr>
<tr class="even">
<td align="left">SQL_BE_10 SQL Order of Precedence</td>
<td align="left">dvdrental.information_schema</td>
<td align="left">VIEW</td>
<td align="left">column_privileges</td>
<td align="left">table_schema = ‘information_schema’ AND table_name like ‘%col%’ and table_type = ‘VIEW’</td>
</tr>
<tr class="odd">
<td align="left">SQL_BE_10 SQL Order of Precedence</td>
<td align="left">dvdrental.information_schema</td>
<td align="left">VIEW</td>
<td align="left">column_udt_usage</td>
<td align="left">table_schema = ‘information_schema’ AND table_name like ‘%col%’ and table_type = ‘VIEW’</td>
</tr>
<tr class="even">
<td align="left">SQL_BE_10 SQL Order of Precedence</td>
<td align="left">dvdrental.information_schema</td>
<td align="left">VIEW</td>
<td align="left">columns</td>
<td align="left">table_schema = ‘information_schema’ AND table_name like ‘%col%’ and table_type = ‘VIEW’</td>
</tr>
<tr class="odd">
<td align="left">SQL_BE_10 SQL Order of Precedence</td>
<td align="left">dvdrental.information_schema</td>
<td align="left">VIEW</td>
<td align="left">constraint_column_usage</td>
<td align="left">table_schema = ‘information_schema’ AND table_name like ‘%col%’ and table_type = ‘VIEW’</td>
</tr>
<tr class="even">
<td align="left">SQL_BE_10 SQL Order of Precedence</td>
<td align="left">dvdrental.information_schema</td>
<td align="left">VIEW</td>
<td align="left">key_column_usage</td>
<td align="left">table_schema = ‘information_schema’ AND table_name like ‘%col%’ and table_type = ‘VIEW’</td>
</tr>
<tr class="odd">
<td align="left">SQL_BE_10 SQL Order of Precedence</td>
<td align="left">dvdrental.information_schema</td>
<td align="left">VIEW</td>
<td align="left">role_column_grants</td>
<td align="left">table_schema = ‘information_schema’ AND table_name like ‘%col%’ and table_type = ‘VIEW’</td>
</tr>
<tr class="even">
<td align="left">SQL_BE_10 SQL Order of Precedence</td>
<td align="left">dvdrental.information_schema</td>
<td align="left">VIEW</td>
<td align="left">triggered_update_columns</td>
<td align="left">table_schema = ‘information_schema’ AND table_name like ‘%col%’ and table_type = ‘VIEW’</td>
</tr>
<tr class="odd">
<td align="left">SQL_BE_10 SQL Order of Precedence</td>
<td align="left">dvdrental.information_schema</td>
<td align="left">VIEW</td>
<td align="left">view_column_usage</td>
<td align="left">table_schema = ‘information_schema’ AND table_name like ‘%col%’ and table_type = ‘VIEW’</td>
</tr>
<tr class="even">
<td align="left">SQL_BE_10 SQL Order of Precedence</td>
<td align="left">dvdrental.information_schema</td>
<td align="left">VIEW</td>
<td align="left">_pg_foreign_table_columns</td>
<td align="left">table_schema = ‘information_schema’ AND table_name like ‘%col%’ and table_type = ‘VIEW’</td>
</tr>
<tr class="odd">
<td align="left">SQL_BE_10 SQL Order of Precedence</td>
<td align="left">dvdrental.information_schema</td>
<td align="left">VIEW</td>
<td align="left">column_options</td>
<td align="left">table_schema = ‘information_schema’ AND table_name like ‘%col%’ and table_type = ‘VIEW’</td>
</tr>
</tbody>
</table>
<pre><code>* How many rows are in the result set?
* If we combine the result sets from SQL_BE_09 and SQL_BE_10, how many rows should we get.</code></pre>
</div>
<div id="sql_be_11-table-and-column-metadata" class="section level2">
<h2><span class="header-section-number">11.14</span> SQL_BE_11 Table and Column Metadata</h2>
<pre><code>Combine SQL_BE_09 and SQL_BE_10.  
Set table_schema = information_schema
    table_name begins with table% or table_name contains %col%
    table_type = VIEW</code></pre>
<div class="sourceCode" id="cb204"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb204-1" data-line-number="1"><span class="co">#SQL_BE_11: Column Metadata</span></a>
<a class="sourceLine" id="cb204-2" data-line-number="2">SQL_BE_<span class="dv">11</span> &lt;-</a>
<a class="sourceLine" id="cb204-3" data-line-number="3"><span class="st">  </span>DBI<span class="op">::</span><span class="kw">dbGetQuery</span>(</a>
<a class="sourceLine" id="cb204-4" data-line-number="4">  con,</a>
<a class="sourceLine" id="cb204-5" data-line-number="5">  <span class="st">&quot;SELECT &#39;SQL_BE_11 SQL Order of Precedence&#39; SQL_BE</span></a>
<a class="sourceLine" id="cb204-6" data-line-number="6"><span class="st">          ,table_catalog || &#39;.&#39; || table_schema db_info </span></a>
<a class="sourceLine" id="cb204-7" data-line-number="7"><span class="st">          ,table_type</span></a>
<a class="sourceLine" id="cb204-8" data-line-number="8"><span class="st">          ,table_name</span></a>
<a class="sourceLine" id="cb204-9" data-line-number="9"><span class="st">          ,&#39;table_schema = &#39;&#39;information_schema&#39;&#39; table_name like &#39;&#39;table%&#39;&#39;&#39; ||</span></a>
<a class="sourceLine" id="cb204-10" data-line-number="10"><span class="st">           &#39;OR table_name like &#39;&#39;%col%&#39;&#39; table_type = &#39;&#39;VIEW&#39;&#39; &#39; showing</span></a>
<a class="sourceLine" id="cb204-11" data-line-number="11"><span class="st">          </span></a>
<a class="sourceLine" id="cb204-12" data-line-number="12"><span class="st">      FROM information_schema.tables t</span></a>
<a class="sourceLine" id="cb204-13" data-line-number="13"><span class="st">     where table_schema = &#39;information_schema&#39;</span></a>
<a class="sourceLine" id="cb204-14" data-line-number="14"><span class="st">       and table_name like &#39;table%&#39; OR table_name like &#39;%col%&#39;</span></a>
<a class="sourceLine" id="cb204-15" data-line-number="15"><span class="st">       and table_type = &#39;VIEW&#39;</span></a>
<a class="sourceLine" id="cb204-16" data-line-number="16"><span class="st">     ORDER BY table_type</span></a>
<a class="sourceLine" id="cb204-17" data-line-number="17"><span class="st">  &quot;</span>  )</a>
<a class="sourceLine" id="cb204-18" data-line-number="18"><span class="kw">display_rs</span>(MODE,SQL_BE_<span class="dv">11</span>,display_rows)</a></code></pre></div>
<table>
<thead>
<tr class="header">
<th align="left">sql_be</th>
<th align="left">db_info</th>
<th align="left">table_type</th>
<th align="left">table_name</th>
<th align="left">showing</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">SQL_BE_11 SQL Order of Precedence</td>
<td align="left">dvdrental.information_schema</td>
<td align="left">VIEW</td>
<td align="left">collations</td>
<td align="left">table_schema = ‘information_schema’ table_name like ‘table%’OR table_name like’%col%’ table_type = ‘VIEW’</td>
</tr>
<tr class="even">
<td align="left">SQL_BE_11 SQL Order of Precedence</td>
<td align="left">dvdrental.information_schema</td>
<td align="left">VIEW</td>
<td align="left">collation_character_set_applicability</td>
<td align="left">table_schema = ‘information_schema’ table_name like ‘table%’OR table_name like’%col%’ table_type = ‘VIEW’</td>
</tr>
<tr class="odd">
<td align="left">SQL_BE_11 SQL Order of Precedence</td>
<td align="left">dvdrental.information_schema</td>
<td align="left">VIEW</td>
<td align="left">column_domain_usage</td>
<td align="left">table_schema = ‘information_schema’ table_name like ‘table%’OR table_name like’%col%’ table_type = ‘VIEW’</td>
</tr>
<tr class="even">
<td align="left">SQL_BE_11 SQL Order of Precedence</td>
<td align="left">dvdrental.information_schema</td>
<td align="left">VIEW</td>
<td align="left">column_privileges</td>
<td align="left">table_schema = ‘information_schema’ table_name like ‘table%’OR table_name like’%col%’ table_type = ‘VIEW’</td>
</tr>
<tr class="odd">
<td align="left">SQL_BE_11 SQL Order of Precedence</td>
<td align="left">dvdrental.information_schema</td>
<td align="left">VIEW</td>
<td align="left">column_udt_usage</td>
<td align="left">table_schema = ‘information_schema’ table_name like ‘table%’OR table_name like’%col%’ table_type = ‘VIEW’</td>
</tr>
<tr class="even">
<td align="left">SQL_BE_11 SQL Order of Precedence</td>
<td align="left">dvdrental.information_schema</td>
<td align="left">VIEW</td>
<td align="left">columns</td>
<td align="left">table_schema = ‘information_schema’ table_name like ‘table%’OR table_name like’%col%’ table_type = ‘VIEW’</td>
</tr>
<tr class="odd">
<td align="left">SQL_BE_11 SQL Order of Precedence</td>
<td align="left">dvdrental.information_schema</td>
<td align="left">VIEW</td>
<td align="left">constraint_column_usage</td>
<td align="left">table_schema = ‘information_schema’ table_name like ‘table%’OR table_name like’%col%’ table_type = ‘VIEW’</td>
</tr>
<tr class="even">
<td align="left">SQL_BE_11 SQL Order of Precedence</td>
<td align="left">dvdrental.information_schema</td>
<td align="left">VIEW</td>
<td align="left">key_column_usage</td>
<td align="left">table_schema = ‘information_schema’ table_name like ‘table%’OR table_name like’%col%’ table_type = ‘VIEW’</td>
</tr>
<tr class="odd">
<td align="left">SQL_BE_11 SQL Order of Precedence</td>
<td align="left">dvdrental.information_schema</td>
<td align="left">VIEW</td>
<td align="left">role_column_grants</td>
<td align="left">table_schema = ‘information_schema’ table_name like ‘table%’OR table_name like’%col%’ table_type = ‘VIEW’</td>
</tr>
<tr class="even">
<td align="left">SQL_BE_11 SQL Order of Precedence</td>
<td align="left">dvdrental.information_schema</td>
<td align="left">VIEW</td>
<td align="left">table_constraints</td>
<td align="left">table_schema = ‘information_schema’ table_name like ‘table%’OR table_name like’%col%’ table_type = ‘VIEW’</td>
</tr>
<tr class="odd">
<td align="left">SQL_BE_11 SQL Order of Precedence</td>
<td align="left">dvdrental.information_schema</td>
<td align="left">VIEW</td>
<td align="left">table_privileges</td>
<td align="left">table_schema = ‘information_schema’ table_name like ‘table%’OR table_name like’%col%’ table_type = ‘VIEW’</td>
</tr>
<tr class="even">
<td align="left">SQL_BE_11 SQL Order of Precedence</td>
<td align="left">dvdrental.information_schema</td>
<td align="left">VIEW</td>
<td align="left">tables</td>
<td align="left">table_schema = ‘information_schema’ table_name like ‘table%’OR table_name like’%col%’ table_type = ‘VIEW’</td>
</tr>
<tr class="odd">
<td align="left">SQL_BE_11 SQL Order of Precedence</td>
<td align="left">dvdrental.information_schema</td>
<td align="left">VIEW</td>
<td align="left">triggered_update_columns</td>
<td align="left">table_schema = ‘information_schema’ table_name like ‘table%’OR table_name like’%col%’ table_type = ‘VIEW’</td>
</tr>
<tr class="even">
<td align="left">SQL_BE_11 SQL Order of Precedence</td>
<td align="left">dvdrental.information_schema</td>
<td align="left">VIEW</td>
<td align="left">view_column_usage</td>
<td align="left">table_schema = ‘information_schema’ table_name like ‘table%’OR table_name like’%col%’ table_type = ‘VIEW’</td>
</tr>
<tr class="odd">
<td align="left">SQL_BE_11 SQL Order of Precedence</td>
<td align="left">dvdrental.information_schema</td>
<td align="left">VIEW</td>
<td align="left">_pg_foreign_table_columns</td>
<td align="left">table_schema = ‘information_schema’ table_name like ‘table%’OR table_name like’%col%’ table_type = ‘VIEW’</td>
</tr>
<tr class="even">
<td align="left">SQL_BE_11 SQL Order of Precedence</td>
<td align="left">dvdrental.information_schema</td>
<td align="left">VIEW</td>
<td align="left">column_options</td>
<td align="left">table_schema = ‘information_schema’ table_name like ‘table%’OR table_name like’%col%’ table_type = ‘VIEW’</td>
</tr>
</tbody>
</table>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="joins-and-complex-queries-13.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="sql-be-12-and-or-logical-precedence.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/smithjd/sql-pet/edit/master/15-sql_quick_start_simple_retrieval.Rmd",
"text": "Edit"
},
"download": ["r-database-docker.pdf"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdn.bootcss.com/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(src))
      src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
