---
title: "Get and Install dvdrental database in Postgres - version c"
author: "John D. Smith (with mods by Scott Came)"
date: "9/3/2018"
output: github_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(DBI)
library(RPostgres)
```
## Create a Postgres container, restore dvdrental database, test connection

## verify that Docker is up and running:
```{r}

system2("docker", "version", stdout = TRUE, stderr = TRUE)

# build an image that derives from postgres:9.4, defined in dvdrental.Dockerfile, that is set up to restore and load the dvdrental db on startup

system2("docker", "build -t postgres-dvdrental -f dvdrental.Dockerfile .", stdout = TRUE, stderr = TRUE)

# run docker to bring up postgres.  The first time it runs it will take a minute to create the Postgres environment.

wd <- getwd()

docker_cmd <- paste0(
  "run -d --name pet --publish 5432:5432 ",
  '--mount "type=bind,source=', wd,
  '/,target=/petdir"',
    " postgres-dvdrental"
)

system2("docker", docker_cmd, stdout = TRUE, stderr = TRUE)

```
now connect to the database with R
```{r}
# need to wait for Docker & Postgres to come up before connecting.
Sys.sleep(5) 

con <- DBI::dbConnect(RPostgres::Postgres(),
                      host = "localhost",
                      port = "5432",
                      user = "postgres",
                      password = "postgres",
                      dbname = "dvdrental" ) # note that the dbname is specified

dbListTables(con)

dbListFields(con, "rental")
dbDisconnect(con)
```
Stop the container
```{r}
system2('docker', 'stop pet',
        stdout = TRUE, stderr = TRUE)
```
Restart the container and verify that the dvdrental database is still there
```{r}
docker_cmd <- paste0(
  "start pet"
)

system2("docker", docker_cmd, stdout = TRUE, stderr = TRUE)

Sys.sleep(1) # need to wait for Docker & Postgres to come up before connecting.

con <- DBI::dbConnect(RPostgres::Postgres(),
                      host = "localhost",
                      port = "5432",
                      user = "postgres",
                      password = "postgres",
                      dbname = "dvdrental" ) # note that the dbname is specified

dbListTables(con)

dbListFields(con, "rental")
dbDisconnect(con)

```

Stop the container & show that it is still there, so can be started again.
```{r}
system2('docker', 'stop pet',
        stdout = TRUE, stderr = TRUE)

# show that the container still exists
system2('docker', 'ps -a',
        stdout = TRUE, stderr = TRUE)

#
# Once stopped, the container could be removed with:
#
# system2('docker', 'rm pet ',
#         stdout = TRUE, stderr = TRUE)

```
